Repository hmcts/opal-frontend, pull requests merged in 2024-01, with the labels that each got.

#71 Po 116
  angular.json
  cypress/support/step_definitions/accountSearch/accountSearch.ts
  package.json
  src/app/app.component.html
  src/app/app.module.ts
  src/app/components/govuk-pagination/govuk-pagination.component.html
  src/app/components/govuk-pagination/govuk-pagination.component.scss
  src/app/components/govuk-pagination/govuk-pagination.component.spec.ts
  src/app/components/govuk-pagination/govuk-pagination.component.ts
  src/app/components/index.ts
  src/app/constants/account-enquiry-default-state.ts
  src/app/constants/index.ts
  src/app/enums/account-enquiry-routes.ts
  src/app/enums/api-paths.ts
  src/app/enums/index.ts
  src/app/interceptors/http-error/http-error.interceptor.spec.ts
  src/app/interceptors/http-error/http-error.interceptor.ts
  src/app/interceptors/index.ts
  src/app/interfaces/account-enquiry-state.interface.ts
  src/app/interfaces/index.ts
  src/app/interfaces/search-defendant-account-body.ts
  src/app/interfaces/search-defendant-accounts.interface.ts
  src/app/mocks/index.ts
  src/app/mocks/search-defendant-accounts.mock.ts
  src/app/mocks/search-state.mock.ts
  src/app/pages/account-enquiry/account-enquiry.component.spec.ts
  src/app/pages/account-enquiry/account-enquiry.component.ts
  src/app/pages/account-enquiry/matches/matches-table/matches-table.component.html
  src/app/pages/account-enquiry/matches/matches-table/matches-table.component.scss
  src/app/pages/account-enquiry/matches/matches-table/matches-table.component.spec.ts
  src/app/pages/account-enquiry/matches/matches-table/matches-table.component.ts
  src/app/pages/account-enquiry/matches/matches.component.html
  src/app/pages/account-enquiry/matches/matches.component.spec.ts
  src/app/pages/account-enquiry/matches/matches.component.ts
  src/app/pages/account-enquiry/search/search.component.html
  src/app/pages/account-enquiry/search/search.component.spec.ts
  src/app/pages/account-enquiry/search/search.component.ts
  src/app/pages/sign-in/sign-in.component.ts
  src/app/pages/test-page/test-page.component.ts
  src/app/services/defendant-account-service/defendant-account.service.spec.ts
  src/app/services/defendant-account-service/defendant-account.service.ts
  src/app/services/state-service/state.service.spec.ts
  src/app/services/state-service/state.service.ts
  src/index.html
  src/styles.scss
  tsconfig.json
  yarn.lock
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-71

#96 Add yarn-audit-known-issues file with vulnerability details
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-96

#98 Fix vulnerability in follow-redirects package
  yarn-audit-known-issues
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-98

#103 Revert applicationinsights version to 2.9.1
  package.json
  yarn.lock
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-103

#108 Update applicationinsights version in package.json
  package.json
  yarn.lock
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-108

#107 Add opal-fines-service into PR/dev env
  charts/opal-frontend/Chart.yaml
  charts/opal-frontend/values.dev.template.yaml
  charts/opal-frontend/values.yaml
  config/custom-environment-variables.json
Labels: ns:opal, prd:opal, enable_keep_helm, rel:opal-frontend-pr-107

#112 Po 117
  cypress/e2e/functional/PO-117_accountDetails.feature
  cypress/support/step_definitions/accountDetails/accountDetails.ts
  cypress/support/step_definitions/accountMatches/accountMatches.ts
  src/app/app-routing.module.ts
  src/app/components/govuk-accordion/govuk-accordion.component.spec.ts
  src/app/components/govuk-summary-list/govuk-summary-list-row/govuk-summary-list-row.component.html
  src/app/components/govuk-summary-list/govuk-summary-list-row/govuk-summary-list-row.component.spec.ts
  src/app/components/govuk-summary-list/govuk-summary-list-row/govuk-summary-list-row.component.ts
  src/app/components/govuk-summary-list/govuk-summary-list.component.html
  src/app/components/govuk-summary-list/govuk-summary-list.component.spec.ts
  src/app/components/govuk-summary-list/govuk-summary-list.component.ts
  src/app/components/govuk-tabs/govuk-tab-list-item/govuk-tab-list-item.component.html
  src/app/components/govuk-tabs/govuk-tab-list-item/govuk-tab-list-item.component.spec.ts
  src/app/components/govuk-tabs/govuk-tab-list-item/govuk-tab-list-item.component.ts
  src/app/components/govuk-tabs/govuk-tab-panel/govuk-tab-panel.component.html
  src/app/components/govuk-tabs/govuk-tab-panel/govuk-tab-panel.component.spec.ts
  src/app/components/govuk-tabs/govuk-tab-panel/govuk-tab-panel.component.ts
  src/app/components/govuk-tabs/govuk-tabs.component.html
  src/app/components/govuk-tabs/govuk-tabs.component.spec.ts
  src/app/components/govuk-tabs/govuk-tabs.component.ts
  src/app/components/helpers/add-gds-body-class.ts
  src/app/components/helpers/index.ts
  src/app/enums/api-paths.ts
  src/app/guards/auth/auth.guard.spec.ts
  src/app/guards/helpers/get-guard-with-dummy-url.ts
  src/app/guards/helpers/index.ts
  src/app/guards/helpers/run-auth-guard-with-context.ts
  src/app/guards/signed-in/signed-in.guard.spec.ts
  src/app/interfaces/defendant-account-details.interface.ts
  src/app/interfaces/index.ts
  src/app/interfaces/search-defendant-accounts.interface.ts
  src/app/mocks/defendant-account-details.mock.ts
  src/app/mocks/index.ts
  src/app/mocks/search-defendant-accounts.mock.ts
  src/app/pages/account-enquiry/details/data/account-details.json
  src/app/pages/account-enquiry/details/data/readme.txt
  src/app/pages/account-enquiry/details/details.component.html
  src/app/pages/account-enquiry/details/details.component.spec.ts
  src/app/pages/account-enquiry/details/details.component.ts
  src/app/pages/account-enquiry/matches/matches-table/matches-table.component.html
  src/app/pages/account-enquiry/matches/matches-table/matches-table.component.ts
  src/app/services/defendant-account-service/defendant-account.service.ts
  src/app/services/index.ts
  src/app/services/utils/utils.service.spec.ts
  src/app/services/utils/utils.service.ts
  tsconfig.json
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-112

#121 Add OPAL_API_URL environment variable
  charts/opal-frontend/values.stg.template.yaml
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-121

#128 Add browser-sync dependency
  package.json
  yarn.lock
Labels: ns:opal, prd:opal, add-or-update, rel:opal-frontend-pr-128

#89 Po 72
  charts/opal-frontend/Chart.yaml
  charts/opal-frontend/values.dev.template.yaml
  charts/opal-frontend/values.stg.template.yaml
  charts/opal-frontend/values.yaml
  config/custom-environment-variables.json
  config/default.json
  cypress.config.ts
  cypress/e2e/functional/PO-115_accountSearch.feature
  cypress/e2e/functional/PO-116_accountMatches.feature
  cypress/e2e/functional/PO-117_accountDetails.feature
  cypress/e2e/smoke/signInTest.feature
  cypress/support/step_definitions/accountDetails/accountDetails.ts
  cypress/support/step_definitions/signInPage/signInTest.ts
  package.json
  server/routes.ts
  server/sso/sso-authenticated.ts
  server/sso/sso-login-callback.ts
  server/sso/sso-login.ts
  server/sso/sso-logout.ts
  server/stubs/sso/index.ts
  server/stubs/sso/sso-authenticated.stub.ts
  server/stubs/sso/sso-login-callback.stub.ts
  server/stubs/sso/sso-login.stub.ts
  server/stubs/sso/sso-logout-callback.stub.ts
  server/stubs/sso/sso-logout.stub.ts
  yarn.lock
Labels: ns:opal, prd:opal, enable_keep_helm, rel:opal-frontend-pr-89

#132 Remove redundant code for token check
  server/sso/sso-authenticated.ts
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-132

#133 automated tests for PO-151
  cypress/e2e/smoke/PO-151_signOutTest.feature
  cypress/support/step_definitions/signInPage/signOutTest.ts
Labels: ns:opal, prd:opal, enable_keep_helm, rel:opal-frontend-pr-133

#139 Added logging
  server/routes.ts
  server/sso/sso-authenticated.ts
  server/sso/sso-login-callback.ts
  server/sso/sso-login.ts
  server/sso/sso-logout-callback.ts
  server/sso/sso-logout.ts
  server/stubs/sso/sso-authenticated.stub.ts
  server/stubs/sso/sso-login-callback.stub.ts
  server/stubs/sso/sso-login.stub.ts
  server/stubs/sso/sso-logout-callback.stub.ts
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-139

#146 Refactor SSO login route to handle errors and redirects
  server/routes.ts
  server/sso/sso-login.ts
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-146

#152 Fix error handling in sso-logout module
  server/sso/sso-logout.ts
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-152

#155 Enable Redis feature flag in values.yaml
  charts/opal-frontend/Chart.yaml
  charts/opal-frontend/values.yaml
  config/custom-environment-variables.json
  config/default.json
  package.json
  server.ts
  server/session/index.ts
  server/session/session-storage.ts
  server/session/session.ts
  server/sso/sso-logout-callback.ts
  server/stubs/sso/sso-login-callback.stub.ts
  server/stubs/sso/sso-logout-callback.stub.ts
  yarn.lock
Labels: ns:opal, prd:opal, enable_keep_helm, rel:opal-frontend-pr-155

#163 Enable redis
  server.ts
  server/session/index.ts
  server/session/session-storage.ts
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-163

#165 Revert "Added 504 logging"
  server/sso/sso-login-callback.ts
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-165

#166 Added 504 logging
  server/sso/sso-login-callback.ts
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-166

#167 Added 504 logging
  server/sso/sso-login-callback.ts
  server/stubs/sso/sso-login-callback.stub.ts
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-167

#170 Added 504 logging
  charts/opal-frontend/Chart.yaml
  charts/opal-frontend/values.yaml
  server/sso/sso-login-callback.ts
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-170

#174 Added 504 logging
  server/sso/sso-logout.ts
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-174

#177 Test change to way logincallback called
  server/routes.ts
  server/sso/sso-login-callback.ts
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-177

#180 Revert "Test change to way logincallback called"
  server/routes.ts
  server/routes_2.ts
  server/sso/sso-login-callback.ts
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-180

#182 Staging sso test
  server/sso/sso-login-callback.ts
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-182

#183 Staging sso test
  server/routes_2.ts
  server/sso/sso-authenticated.ts
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-183

#185 Add logging for user authentication
  server/sso/sso-authenticated.ts
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-185

#188 Add Redis connection and ping logging
  server/session/session-storage.ts
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-188
