Repository hmcts/opal-frontend, pull requests merged in 2024-10, with the labels that each got.

#912 Missing AC now covered. Also, fixed MoJ Date Picker excluding ability to choose weekend dates
  cypress/e2e/functional/opal/manualAccountCreation/paymentTerms/PO-548_enforcementActionAdultOrYouth.feature
  src/app/components/moj/moj-date-picker/moj-date-picker.component.html
  src/app/components/moj/moj-date-picker/moj-date-picker.component.ts
  src/app/flows/fines/fines-mac/fines-mac-payment-terms/fines-mac-payment-terms-form/fines-mac-payment-terms-form.component.html
Labels: ns:opal, prd:opal, test_mac, rel:opal-frontend-pr-912

#916 Xml test reports
  Jenkinsfile_CNP
  cypress/parallel/weights/smoke-parallel-weights.json
  cypress/reports/functionalXmlReport.html
  cypress/reports/smokeXmlReport.html
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-916

#913 PO-808: Payment Terms - Remove 2003 Validation
  cypress/e2e/functional/opal/manualAccountCreation/paymentTerms/PO-471_collectionOrder_adultOrYouth.feature
  cypress/e2e/functional/opal/manualAccountCreation/paymentTerms/PO-649_collectionOrder_AY-PG.feature
  src/app/flows/fines/fines-mac/fines-mac-payment-terms/constants/fines-mac-payment-terms-collection-order-options-control-validation.ts
  src/app/flows/fines/fines-mac/fines-mac-payment-terms/constants/fines-mac-payment-terms-field-errors.ts
Labels: ns:opal, prd:opal, test_mac, rel:opal-frontend-pr-913

#934 Update yarn-audit-known-issues
  yarn-audit-known-issues
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-934

#941 PO-413
  cypress/e2e/functional/opal/manualAccountCreation/addOffence/PO-413_majorCreditorAdultOrYouth.feature
  cypress/e2e/functional/opal/manualAccountCreation/addOffence/PO-817_majorCreditorAY-PG.feature
  cypress/e2e/functional/opal/manualAccountCreation/addOffence/PO-818_majorCreditorCompany.feature
  cypress/support/step_definitions/genericSteps/errorMessageSteps.ts
  cypress/support/step_definitions/genericSteps/inputFieldSteps.ts
  src/app/components/abstract/abstract-form-array-base/abstract-form-array-base.spec.ts
  src/app/components/abstract/abstract-form-array-base/abstract-form-array-base.ts
  src/app/flows/fines/fines-mac/fines-mac-account-comments-notes/fines-mac-account-comments-notes-form/fines-mac-account-comments-notes-form.component.spec.ts
  src/app/flows/fines/fines-mac/fines-mac-offence-details/constants/fines-mac-offence-details-creditor-options.constant.ts
  src/app/flows/fines/fines-mac/fines-mac-offence-details/constants/fines-mac-offence-details-draft-state.constant.ts
  src/app/flows/fines/fines-mac/fines-mac-offence-details/constants/fines-mac-offence-details-form.constant.ts
  src/app/flows/fines/fines-mac/fines-mac-offence-details/constants/fines-mac-offence-details-imposition-field-names.constant.ts
  src/app/flows/fines/fines-mac/fines-mac-offence-details/constants/fines-mac-offence-details-impositions-field-errors.constant.ts
  src/app/flows/fines/fines-mac/fines-mac-offence-details/constants/fines-mac-offence-details-impositions-state.constant.ts
  src/app/flows/fines/fines-mac/fines-mac-offence-details/constants/fines-mac-offence-details-impositions.constant.ts
  src/app/flows/fines/fines-mac/fines-mac-offence-details/constants/fines-mac-offence-details-offences-field-errors.constant.ts
  src/app/flows/fines/fines-mac/fines-mac-offence-details/constants/fines-mac-offence-details-result-codes.constant.ts
  src/app/flows/fines/fines-mac/fines-mac-offence-details/constants/fines-mac-offence-details-state.constant.ts
  src/app/flows/fines/fines-mac/fines-mac-offence-details/fines-mac-offence-details-add-an-offence/fines-mac-offence-details-add-an-offence-form/fines-mac-offence-details-add-an-offence-form.component.html
  src/app/flows/fines/fines-mac/fines-mac-offence-details/fines-mac-offence-details-add-an-offence/fines-mac-offence-details-add-an-offence-form/fines-mac-offence-details-add-an-offence-form.component.spec.ts
  src/app/flows/fines/fines-mac/fines-mac-offence-details/fines-mac-offence-details-add-an-offence/fines-mac-offence-details-add-an-offence-form/fines-mac-offence-details-add-an-offence-form.component.ts
  src/app/flows/fines/fines-mac/fines-mac-offence-details/fines-mac-offence-details-add-an-offence/fines-mac-offence-details-add-an-offence.component.html
  src/app/flows/fines/fines-mac/fines-mac-offence-details/fines-mac-offence-details-add-an-offence/fines-mac-offence-details-add-an-offence.component.spec.ts
  src/app/flows/fines/fines-mac/fines-mac-offence-details/fines-mac-offence-details-add-an-offence/fines-mac-offence-details-add-an-offence.component.ts
  src/app/flows/fines/fines-mac/fines-mac-offence-details/fines-mac-offence-details-remove-imposition/fines-mac-offence-details-remove-imposition.component.html
  src/app/flows/fines/fines-mac/fines-mac-offence-details/fines-mac-offence-details-remove-imposition/fines-mac-offence-details-remove-imposition.component.spec.ts
  src/app/flows/fines/fines-mac/fines-mac-offence-details/fines-mac-offence-details-remove-imposition/fines-mac-offence-details-remove-imposition.component.ts
  src/app/flows/fines/fines-mac/fines-mac-offence-details/fines-mac-offence-details-search-offences/fines-mac-offence-details-search-offences.component.ts
  src/app/flows/fines/fines-mac/fines-mac-offence-details/fines-mac-offence-details.component.spec.ts
  src/app/flows/fines/fines-mac/fines-mac-offence-details/fines-mac-offence-details.component.ts
  src/app/flows/fines/fines-mac/fines-mac-offence-details/interfaces/fines-mac-offence-details-creditor-option-control-validation.interface.ts
  src/app/flows/fines/fines-mac/fines-mac-offence-details/interfaces/fines-mac-offence-details-impositions-state.interface.ts
  src/app/flows/fines/fines-mac/fines-mac-offence-details/mocks/fines-mac-offence-details-draft-state.mock.ts
  src/app/flows/fines/fines-mac/fines-mac-offence-details/mocks/fines-mac-offence-details-state.mock.ts
  src/app/flows/fines/fines-mac/fines-mac-offence-details/routing/constants/fines-mac-offence-details-routing-paths.constant.ts
  src/app/flows/fines/fines-mac/fines-mac-offence-details/routing/fines-mac-offence-details.routes.ts
  src/app/flows/fines/fines-mac/fines-mac-offence-details/services/fines-mac-offence-details-service/fines-mac-offence-details.service.spec.ts
  src/app/flows/fines/fines-mac/fines-mac-offence-details/services/fines-mac-offence-details-service/fines-mac-offence-details.service.ts
  src/app/flows/fines/fines-mac/mocks/fines-mac-state.mock.ts
  src/app/flows/fines/fines-mac/routing/fines-mac.routes.ts
  src/app/flows/fines/services/opal-fines-service/constants/opal-fines-paths.constant.ts
  src/app/flows/fines/services/opal-fines-service/interfaces/opal-fines-major-creditor-ref-data.interface.ts
  src/app/flows/fines/services/opal-fines-service/interfaces/opal-fines-paths.interface.ts
  src/app/flows/fines/services/opal-fines-service/mocks/opal-fines-major-creditor-autocomplete-items.mock.ts
  src/app/flows/fines/services/opal-fines-service/mocks/opal-fines-major-creditor-pretty-name.mock.ts
  src/app/flows/fines/services/opal-fines-service/mocks/opal-fines-major-creditor-ref-data.mock.ts
  src/app/flows/fines/services/opal-fines-service/opal-fines.service.spec.ts
  src/app/flows/fines/services/opal-fines-service/opal-fines.service.ts
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-941

#937 Changed static dates to new date steps
  cypress/e2e/functional/opal/manualAccountCreation/paymentTerms/PO-471_collectionOrder_adultOrYouth.feature
  cypress/e2e/functional/opal/manualAccountCreation/paymentTerms/PO-592_companyAdditionalFields.feature
  cypress/e2e/functional/opal/manualAccountCreation/paymentTerms/PO-649_collectionOrder_AY-PG.feature
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-937

#979 Critters depending - known issues
  yarn-audit-known-issues
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-979

#981 Po 909
  src/app/flows/fines/fines-mac/fines-mac-payment-terms/constants/fines-mac-payment-terms-frequency-options.ts
  src/app/flows/fines/fines-mac/fines-mac-payment-terms/interfaces/fines-mac-payment-terms-frequency-options.interface.ts
  src/app/flows/fines/fines-mac/services/fines-mac-payload/utils/fines-mac-payload-payment-terms.utils.spec.ts
  src/app/flows/fines/fines-mac/services/fines-mac-payload/utils/fines-mac-payload-payment-terms.utils.ts
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-981

#982 Po 908
  src/app/components/govuk/govuk-radio/govuk-radios-item/govuk-radios-item.component.ts
  src/app/flows/fines/fines-mac/fines-mac-payment-terms/constants/fines-mac-payment-terms-collection-order-options-control-validation.ts
  src/app/flows/fines/fines-mac/fines-mac-payment-terms/fines-mac-payment-terms-form/fines-mac-payment-terms-form.component.html
  src/app/flows/fines/fines-mac/fines-mac-payment-terms/fines-mac-payment-terms-form/fines-mac-payment-terms-form.component.spec.ts
  src/app/flows/fines/fines-mac/fines-mac-payment-terms/interfaces/fines-mac-payment-terms-collection-order-options-control-validation.interface.ts
  src/app/flows/fines/fines-mac/services/fines-mac-payload/utils/fines-mac-payload-payment-terms.utils.spec.ts
  src/app/flows/fines/fines-mac/services/fines-mac-payload/utils/fines-mac-payload-payment-terms.utils.ts
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-982
