Repository hmcts/opal-frontend, pull requests merged in 2024-04, with the labels that each got.

#381 Fix authentication error handling in AuthService
  cypress/support/step_definitions/signInPage/signInTest.ts
  src/app/services/auth-service/auth.service.spec.ts
  src/app/services/auth-service/auth.service.ts
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-381

#384 Remove max age to align with DARTS
  config/default.json
  package.json
  yarn.lock
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-384

#389 Update tar dependency to version 6.2.1
  package.json
  yarn.lock
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-389

#392 Jwt token exp
  config/default.json
  server/sso/sso-authenticated.ts
  server/stubs/sso/sso-authenticated.stub.ts
  server/utils/base64.ts
  server/utils/index.ts
  server/utils/jwt.ts
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-392

#402 Update Cypress test commands to use Chrome browser
  package.json
  src/app/services/session-service/session.service.ts
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-402

#408 Po 271
  cypress/e2e/functional/opal/PO-115_accountSearch.feature
  cypress/e2e/functional/opal/PO-116_accountMatches.feature
  cypress/e2e/functional/opal/PO-117_accountDetails.feature
  cypress/e2e/functional/opal/PO-136_PO-137_accountHistory.feature
  cypress/e2e/functional/opal/PO-251_unauthorisedUser.feature
  cypress/e2e/smoke/opal/PO-151_signOutTest.feature
  cypress/e2e/smoke/opal/PO-224_accessibilityTests.feature
  cypress/e2e/smoke/opal/signInTest.feature
  cypress/support/step_definitions/signInPage/signInTest.ts
  server/session/user-state.ts
  server/sso/sso-login-callback.ts
  src/app/app-routing.module.ts
  src/app/components/govuk-header/govuk-header.component.html
  src/app/enums/routing-paths.ts
  src/app/pages/account-enquiry/details/details.component.spec.ts
  src/app/pages/account-enquiry/details/details.component.ts
  src/app/pages/dashboard/dashboard.component.html
  src/app/pages/dashboard/dashboard.component.spec.ts
  src/app/pages/dashboard/dashboard.component.ts
  src/app/pages/test-page/test-page.component.html
  src/app/pages/test-page/test-page.component.spec.ts
  src/app/pages/test-page/test-page.component.ts
  src/app/resolvers/index.ts
  src/app/resolvers/user-state/user-state.resolver.spec.ts
  src/app/resolvers/user-state/user-state.resolver.ts
  src/app/services/app-initializer-service/app-initializer.service.spec.ts
  src/app/services/app-initializer-service/app-initializer.service.ts
  src/app/services/session-service/session.service.spec.ts
  src/app/services/session-service/session.service.ts
  src/app/services/state-service/state.service.ts
  src/index.html
  tsconfig.json
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-408

#417 Switch back to use target as seems to be working now
  server/api/proxy.ts
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-417

#421 Po 293
  .vscode/extensions.json
  angular.json
  cypress/e2e/functional/opal/PO-115_accountSearch.feature
  cypress/e2e/functional/opal/PO-116_accountMatches.feature
  cypress/support/step_definitions/accountSearch/accountSearch.ts
  package.json
  src/app/components/alphagov/alphagov-accessible-autocomplete/alphagov-accessible-autocomplete.component.html
  src/app/components/alphagov/alphagov-accessible-autocomplete/alphagov-accessible-autocomplete.component.scss
  src/app/components/alphagov/alphagov-accessible-autocomplete/alphagov-accessible-autocomplete.component.spec.ts
  src/app/components/alphagov/alphagov-accessible-autocomplete/alphagov-accessible-autocomplete.component.ts
  src/app/components/index.ts
  src/app/interfaces/auto-complete-item.interface.ts
  src/app/interfaces/index.ts
  src/app/mocks/auto-complete-items.mock.ts
  src/app/mocks/index.ts
  src/app/pages/account-enquiry/search/search-form/search-form.component.html
  src/app/pages/account-enquiry/search/search-form/search-form.component.spec.ts
  src/app/pages/account-enquiry/search/search-form/search-form.component.ts
  src/app/pages/account-enquiry/search/search.component.ts
  src/app/type.d.ts
  yarn.lock
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-421

#432 Remove tar resolution
  package.json
  yarn.lock
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-432

#438 Remove Superagent Resolution
  package.json
  yarn.lock
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-438

#439 Po 326
  src/app/components/alphagov/alphagov-accessible-autocomplete/alphagov-accessible-autocomplete.component.spec.ts
  src/app/components/alphagov/alphagov-accessible-autocomplete/alphagov-accessible-autocomplete.component.ts
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-439
