Repository hmcts/opal-frontend, pull requests merged in 2024-02, with the labels that each got.

#217 Logout redirect
  cypress/support/step_definitions/signInPage/signInTest.ts
  server/sso/sso-logout.ts
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-217

#220 Update SSO login callback stub to use GET request for token retrieval
  server/stubs/sso/sso-login-callback.stub.ts
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-220

#206 Po 136
  config/default.json
  cypress/e2e/functional/PO-136_accountNotes.feature
  cypress/support/step_definitions/accountDetails/accountHistory.ts
  src/app/enums/api-paths.ts
  src/app/interfaces/add-defendant-account-note-body.ts
  src/app/interfaces/defendant-account-note.ts
  src/app/interfaces/index.ts
  src/app/mocks/add-defendant-account-note.mock.ts
  src/app/mocks/defendant-account-note.mock.ts
  src/app/mocks/index.ts
  src/app/pages/account-enquiry/details/details.component.html
  src/app/pages/account-enquiry/details/details.component.scss
  src/app/pages/account-enquiry/details/details.component.spec.ts
  src/app/pages/account-enquiry/details/details.component.ts
  src/app/services/defendant-account-service/defendant-account.service.spec.ts
  src/app/services/defendant-account-service/defendant-account.service.ts
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-206

#207 Po 137
  cypress/e2e/functional/PO-136_PO-137_accountHistory.feature
  cypress/e2e/functional/PO-136_accountNotes.feature
  cypress/support/step_definitions/accountDetails/accountHistory.ts
  src/app/components/govuk-inset-text/govuk-inset-text.component.html
  src/app/components/govuk-inset-text/govuk-inset-text.component.scss
  src/app/components/govuk-inset-text/govuk-inset-text.component.spec.ts
  src/app/components/govuk-inset-text/govuk-inset-text.component.ts
  src/app/components/index.ts
  src/app/enums/api-paths.ts
  src/app/interfaces/defendant-account-note.ts
  src/app/mocks/defendant-account-notes.mock.ts
  src/app/mocks/index.ts
  src/app/pages/account-enquiry/details/details.component.html
  src/app/pages/account-enquiry/details/details.component.spec.ts
  src/app/pages/account-enquiry/details/details.component.ts
  src/app/services/defendant-account-service/defendant-account.service.spec.ts
  src/app/services/defendant-account-service/defendant-account.service.ts
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-207

#243 Add yarn-audit-known-issues file with details of high severity vulner…
  yarn-audit-known-issues
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-243

#244 Remove defendantAccountDetails enum value and update getDefendantAcco…
  src/app/enums/api-paths.ts
  src/app/services/defendant-account-service/defendant-account.service.spec.ts
  src/app/services/defendant-account-service/defendant-account.service.ts
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-244

#242 Po 201
  angular.json
  package.json
  src/app/app-routing.module.ts
  src/app/components/govuk-header/govuk-header.component.html
  src/app/components/govuk-header/govuk-header.component.scss
  src/app/components/index.ts
  src/app/components/moj-sub-navigation/moj-sub-navigation-item/moj-sub-navigation-item.component.html
  src/app/components/moj-sub-navigation/moj-sub-navigation-item/moj-sub-navigation-item.component.scss
  src/app/components/moj-sub-navigation/moj-sub-navigation-item/moj-sub-navigation-item.component.spec.ts
  src/app/components/moj-sub-navigation/moj-sub-navigation-item/moj-sub-navigation-item.component.ts
  src/app/components/moj-sub-navigation/moj-sub-navigation.component.html
  src/app/components/moj-sub-navigation/moj-sub-navigation.component.scss
  src/app/components/moj-sub-navigation/moj-sub-navigation.component.spec.ts
  src/app/components/moj-sub-navigation/moj-sub-navigation.component.ts
  src/app/pages/account-enquiry/search/search.component.ts
  src/styles.scss
  yarn.lock
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-242

#236 csrf test
  config/default.json
  package.json
  server.ts
  server/csrf-token/csrf-token.ts
  server/csrf-token/index.ts
  server/session/session-storage.ts
  server/sso/sso-logout-callback.ts
  src/app/app.module.ts
  src/app/pages/account-enquiry/details/details.component.html
  src/app/pages/account-enquiry/details/details.component.ts
  src/app/pages/account-enquiry/matches/matches-table/matches-table.component.html
  src/app/pages/account-enquiry/matches/matches-table/matches-table.component.spec.ts
  src/app/pages/account-enquiry/matches/matches-table/matches-table.component.ts
  src/app/pages/account-enquiry/matches/matches.component.html
  src/app/pages/account-enquiry/matches/matches.component.spec.ts
  src/app/pages/account-enquiry/matches/matches.component.ts
  yarn.lock
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-236

#248 Add node-ip package and remove yarn-audit-known-issues file
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-248

#246 Use keyvault values for user sign in
  Jenkinsfile_CNP
  cypress.config.ts
  cypress/support/step_definitions/signInPage/signInTest.ts
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-246

#247 Refactor server.ts and helmet/index.ts***
  charts/opal-frontend/Chart.yaml
  charts/opal-frontend/values.yaml
  config/custom-environment-variables.json
  config/default.json
  server.ts
  server/modules/helmet/index.ts
  src/index.html
Labels: ns:opal, prd:opal, enable_keep_helm, rel:opal-frontend-pr-247

#253 Add Dynatrace domain to connectSrc directive in Helmet module
  server/modules/helmet/index.ts
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-253

#261 Add cypress axe
  cypress/e2e/functional/PO-115_accountSearch.feature
  cypress/e2e/functional/PO-116_accountMatches.feature
  cypress/e2e/functional/PO-117_accountDetails.feature
  cypress/support/step_definitions/accessibility/accessibility.ts
  cypress/tsconfig.json
  pa11y/pa11y.ts
  pa11y/tsconfig.json
  package.json
  src/app/components/govuk-summary-list/govuk-summary-list-row/govuk-summary-list-row.component.html
  src/app/components/govuk-summary-list/govuk-summary-list-row/govuk-summary-list-row.component.spec.ts
  src/app/components/govuk-summary-list/govuk-summary-list-row/govuk-summary-list-row.component.ts
  src/app/pages/account-enquiry/account-enquiry.component.html
  src/app/pages/account-enquiry/details/details.component.html
  src/app/pages/account-enquiry/matches/matches-table/matches-table.component.html
  src/app/pages/sign-in/sign-in.component.html
  yarn.lock
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-261

#264 Update accessibility test command in README
  README.md
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-264

#267 Adding Accessibility tests to smoke test
  cypress/e2e/functional/PO-115_accountSearch.feature
  cypress/e2e/functional/PO-116_accountMatches.feature
  cypress/e2e/functional/PO-117_accountDetails.feature
  cypress/e2e/smoke/PO-224_accessibilityTests.feature
  cypress/support/step_definitions/accessibility/accessibility.ts
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-267

#268 fix for broad search tests impacted by BE change on defendantSearch
  cypress/e2e/functional/PO-116_accountMatches.feature
  cypress/e2e/functional/PO-117_accountDetails.feature
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-268

#269 Po 225
  cypress/support/step_definitions/accountSearch/accountSearch.ts
  src/app/constants/account-enquiry-default-state.ts
  src/app/interfaces/account-enquiry-state.interface.ts
  src/app/mocks/search-state.mock.ts
  src/app/pages/account-enquiry/search/search.component.html
  src/app/pages/account-enquiry/search/search.component.ts
  src/app/services/defendant-account-service/defendant-account.service.spec.ts
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-269

#270 Po 226
  cypress/e2e/functional/PO-115_accountSearch.feature
  cypress/e2e/functional/PO-116_accountMatches.feature
  src/app/enums/api-paths.ts
  src/app/interfaces/govuk-select-options.interface.ts
  src/app/interfaces/index.ts
  src/app/interfaces/search-court-body.interface.ts
  src/app/interfaces/search-court.interface.ts
  src/app/mocks/index.ts
  src/app/mocks/search-court-body.mock.ts
  src/app/mocks/search-court-select-options.mock.ts
  src/app/mocks/search-court.mock.ts
  src/app/pages/account-enquiry/search/data/ct-list.json
  src/app/pages/account-enquiry/search/data/readme.txt
  src/app/pages/account-enquiry/search/search-form/search-form.component.html
  src/app/pages/account-enquiry/search/search-form/search-form.component.scss
  src/app/pages/account-enquiry/search/search-form/search-form.component.spec.ts
  src/app/pages/account-enquiry/search/search-form/search-form.component.ts
  src/app/pages/account-enquiry/search/search.component.html
  src/app/pages/account-enquiry/search/search.component.spec.ts
  src/app/pages/account-enquiry/search/search.component.ts
  src/app/services/court-service/court.service.spec.ts
  src/app/services/court-service/court.service.ts
  src/app/services/index.ts
  tsconfig.json
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-270

#275 Po 218
  src/app/components/govuk-checkboxes/govuk-checkboxes.component.ts
  src/app/components/govuk-pagination/govuk-pagination.component.ts
  src/app/components/govuk-summary-list/govuk-summary-list-row/govuk-summary-list-row.component.spec.ts
  src/app/components/govuk-summary-list/govuk-summary-list-row/govuk-summary-list-row.component.ts
  src/app/components/helpers/add-gds-body-class.ts
  src/app/interceptors/http-error/http-error.interceptor.ts
  src/app/pages/account-enquiry/details/details.component.ts
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-275

#278 Vscode setup
  .vscode/extensions.json
  .vscode/settings.json
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-278

#283 Cache courts
  src/app/app.module.ts
  src/app/components/govuk-header/govuk-header.component.ts
  src/app/pages/account-enquiry/search/search.component.ts
  src/app/services/auth-service/auth.service.spec.ts
  src/app/services/auth-service/auth.service.ts
  src/app/services/court-service/court.service.spec.ts
  src/app/services/court-service/court.service.ts
  src/app/services/defendant-account-service/defendant-account.service.ts
  src/app/services/state-service/state.service.spec.ts
  src/app/services/state-service/state.service.ts
  tsconfig.json
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-283

#284 Update SecurityToken interface
  server/interfaces/securityToken.ts
  server/interfaces/userState.ts
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-284
