Repository hmcts/opal-frontend, pull requests merged in 2024-03, with the labels that each got.

#285 Fe opal and legacy modes
  cypress.config.ts
  cypress/e2e/functional/legacy/dummyTest.feature
  cypress/e2e/functional/opal/PO-115_accountSearch.feature
  cypress/e2e/functional/opal/PO-116_accountMatches.feature
  cypress/e2e/functional/opal/PO-117_accountDetails.feature
  cypress/e2e/functional/opal/PO-136_PO-137_accountHistory.feature
  cypress/e2e/smoke/legacy/legacySignInTest.feature
  cypress/e2e/smoke/opal/PO-151_signOutTest.feature
  cypress/e2e/smoke/opal/PO-224_accessibilityTests.feature
  cypress/e2e/smoke/opal/signInTest.feature
  cypress/support/step_definitions/modeSwitch/modeSwitch.ts
  package.json
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-285

#302 condition for staging.staging
  cypress/support/step_definitions/modeSwitch/modeSwitch.ts
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-302

#303 Quickfix2 for master pipeline failing
  cypress/support/step_definitions/modeSwitch/modeSwitch.ts
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-303

#304 Add businessUnitId to defendant account interfaces and mocks
  src/app/interfaces/add-defendant-account-note-body.ts
  src/app/interfaces/defendant-account-details.interface.ts
  src/app/mocks/add-defendant-account-note.mock.ts
  src/app/mocks/defendant-account-details.mock.ts
  src/app/pages/account-enquiry/details/details.component.spec.ts
  src/app/pages/account-enquiry/details/details.component.ts
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-304

#299 Launch darkly
  README.md
  charts/opal-frontend/Chart.yaml
  charts/opal-frontend/values.dev.template.yaml
  charts/opal-frontend/values.yaml
  config/custom-environment-variables.json
  config/default.json
  package.json
  server.ts
  server/interfaces/index.ts
  server/interfaces/launchDarklyConfig.ts
  server/launch-darkly/index.ts
  server/launch-darkly/launch-darkly.ts
  server/modules/helmet/index.ts
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/components/govuk-header/govuk-header.component.html
  src/app/components/govuk-header/govuk-header.component.ts
  src/app/interfaces/index.ts
  src/app/interfaces/launch-darkly-config.interface.ts
  src/app/mocks/index.ts
  src/app/mocks/launch-darkly-change-flags.mock.ts
  src/app/mocks/launch-darkly-flags.mock.ts
  src/app/pages/account-enquiry/search/search.component.html
  src/app/pages/sign-in/sign-in.component.html
  src/app/services/index.ts
  src/app/services/launch-darkly/launch-darkly.service.spec.ts
  src/app/services/launch-darkly/launch-darkly.service.ts
  src/app/services/state-service/state.service.ts
  yarn.lock
Labels: ns:opal, prd:opal, enable_keep_helm, rel:opal-frontend-pr-299

#309 separating screenshots for opal and legacy
  package.json
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-309

#311 Add add note flag
  charts/opal-frontend/Chart.yaml
  charts/opal-frontend/values.stg.template.yaml
  charts/opal-frontend/values.yaml
  src/app/pages/account-enquiry/details/details.component.html
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-311

#314 Disable Launch Darkly feature flag in dev and stg environments
  charts/opal-frontend/Chart.yaml
  charts/opal-frontend/values.dev.template.yaml
  charts/opal-frontend/values.stg.template.yaml
  charts/opal-frontend/values.yaml
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-314

#315 Remove lodash dependency
  package.json
  yarn.lock
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-315

#316 Remove test flag from search component HTML
  src/app/pages/account-enquiry/search/search.component.html
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-316

#331 PO-242: Use updated response from backend
  server/stubs/sso/sso-login-callback.stub.ts
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-331

#335 Update values.dev.template.yaml
  charts/opal-frontend/values.dev.template.yaml
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-335

#323 Po 181
  server.ts
  server/interfaces/userState.ts
  server/session.d.ts
  server/session/index.ts
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/components/govuk-header/govuk-header.component.html
  src/app/interfaces/index.ts
  src/app/interfaces/user-state.interface.ts
  src/app/mocks/index.ts
  src/app/mocks/user-state.mock.ts
  src/app/services/app-initializer-service/app-initializer.service.spec.ts
  src/app/services/app-initializer-service/app-initializer.service.ts
  src/app/services/index.ts
  src/app/services/state-service/state.service.ts
  src/app/services/user-state-service/user-state.service.spec.ts
  src/app/services/user-state-service/user-state.service.ts
Labels: ns:opal, prd:opal, add-or-update, rel:opal-frontend-pr-323

#328 test wait longer for backend
  cypress/support/step_definitions/modeSwitch/modeSwitch.ts
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-328

#349 Po 182
  README.md
  config/default.json
  src/app/app-routing.module.ts
  src/app/constants/index.ts
  src/app/constants/route-permissions.ts
  src/app/enums/index.ts
  src/app/enums/permissions-map.ts
  src/app/enums/routing-paths.ts
  src/app/guards/index.ts
  src/app/guards/route-permissions/route-permissions.guard.spec.ts
  src/app/guards/route-permissions/route-permissions.guard.ts
  src/app/interfaces/add-defendant-account-note-body.interface.ts
  src/app/interfaces/defendant-account-note.interface.ts
  src/app/interfaces/index.ts
  src/app/interfaces/permissions.interface.ts
  src/app/interfaces/search-defendant-account-body.interface.ts
  src/app/interfaces/user-state.interface.ts
  src/app/mocks/defendant-account-details.mock.ts
  src/app/pages/access-denied/access-denied.component.html
  src/app/pages/access-denied/access-denied.component.scss
  src/app/pages/access-denied/access-denied.component.spec.ts
  src/app/pages/access-denied/access-denied.component.ts
  src/app/pages/account-enquiry/details/details.component.html
  src/app/pages/account-enquiry/details/details.component.spec.ts
  src/app/pages/account-enquiry/details/details.component.ts
  src/app/services/app-initializer-service/app-initializer.service.ts
  src/app/services/index.ts
  src/app/services/permissions-service/permissions.service.spec.ts
  src/app/services/permissions-service/permissions.service.ts
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-349

#361 Update opal-frontend version to 0.0.53
  charts/opal-frontend/Chart.yaml
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-361
