Repository hmcts/opal-frontend, pull requests merged in 2024-05, with the labels that each got.

#442 Maintainability Code Smells addressed
  src/app/components/alphagov/alphagov-accessible-autocomplete/alphagov-accessible-autocomplete.component.ts
  src/app/components/govuk/govuk-accordion/govuk-accordion.component.ts
  src/app/constants/api-paths.ts
  src/app/constants/index.ts
  src/app/enums/api-paths.ts
  src/app/enums/index.ts
  src/app/services/court-service/court.service.spec.ts
  src/app/services/court-service/court.service.ts
  src/app/services/defendant-account-service/defendant-account.service.spec.ts
  src/app/services/defendant-account-service/defendant-account.service.ts
  src/app/services/permissions-service/permissions.service.ts
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-442

#446 PO-333
  angular.json
  package.json
  src/app/components/index.ts
  src/app/components/scotgov/scotgov-date-picker/scotgov-date-picker.component.html
  src/app/components/scotgov/scotgov-date-picker/scotgov-date-picker.component.spec.ts
  src/app/components/scotgov/scotgov-date-picker/scotgov-date-picker.component.ts
  src/app/pages/dashboard/dashboard.component.ts
  src/app/type.d.ts
  yarn.lock
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-446

#443 Change to angular.json to export the code coverage locally
  README.md
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-443

#459 PO-329
  src/app/components/alphagov/alphagov-accessible-autocomplete/alphagov-accessible-autocomplete.component.spec.ts
  src/app/components/scotgov/scotgov-date-picker/scotgov-date-picker.component.spec.ts
  src/app/guards/index.spec.ts
  src/app/pages/account-enquiry/search/search.component.spec.ts
  src/app/services/permissions-service/permissions.service.spec.ts
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-459

#460 Po 330
  src/app/components/govuk/govuk-text-input/govuk-text-input.component.html
  src/app/components/govuk/govuk-text-input/govuk-text-input.component.ts
  src/app/interfaces/form-control-error.interface.ts
  src/app/interfaces/form-control-errors.interface.ts
  src/app/interfaces/form-error-messages.interface.ts
  src/app/interfaces/form-error-summary-entry.interface.ts
  src/app/interfaces/index.ts
  src/app/mocks/form-control-error.mock.ts
  src/app/mocks/form-error-summary-entry.mock.ts
  src/app/mocks/index.ts
  src/app/pages/account-enquiry/search/search-form/search-form.component.html
  src/app/pages/account-enquiry/search/search-form/search-form.component.spec.ts
  src/app/pages/account-enquiry/search/search-form/search-form.component.ts
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-460

#477 Po 332
  package.json
  src/app/components/govuk/govuk-date-input/govuk-date-input.component.html
  src/app/components/govuk/govuk-date-input/govuk-date-input.component.ts
  src/app/components/govuk/govuk-error-summary/govuk-error-summary.component.html
  src/app/components/govuk/govuk-error-summary/govuk-error-summary.component.spec.ts
  src/app/components/govuk/govuk-error-summary/govuk-error-summary.component.ts
  src/app/components/index.ts
  src/app/interfaces/field-error.interface.ts
  src/app/interfaces/field-errors.interface.ts
  src/app/interfaces/form-control-error-message.interface.ts
  src/app/interfaces/form-control-errors.interface.ts
  src/app/interfaces/form-error-messages.interface.ts
  src/app/interfaces/form-error-summary-message.interface.ts
  src/app/interfaces/form-error.interface.ts
  src/app/interfaces/high-priority-form-error.interface.ts
  src/app/interfaces/index.ts
  src/app/mocks/form-date-error-summary.mock.ts
  src/app/mocks/form-error-summary-entry.mock.ts
  src/app/mocks/index.ts
  src/app/pages/account-enquiry/search/search-form/search-form.component.html
  src/app/pages/account-enquiry/search/search-form/search-form.component.spec.ts
  src/app/pages/account-enquiry/search/search-form/search-form.component.ts
  src/app/pages/dashboard/dashboard.component.ts
  src/app/validators/index.ts
  src/app/validators/over-eighteen/over-eighteen.validator.spec.ts
  src/app/validators/over-eighteen/over-eighteen.validator.ts
  yarn.lock
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-477

#469 Radio button validation added
  src/app/components/govuk/govuk-radios/govuk-radios.component.html
  src/app/components/govuk/govuk-radios/govuk-radios.component.ts
  src/app/pages/account-enquiry/search/config/search-type-radios.ts
  src/app/pages/account-enquiry/search/search-form/search-form.component.spec.ts
  src/app/pages/account-enquiry/search/search-form/search-form.component.ts
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-469

#481 Manual Account Creation Component added
  cypress/e2e/functional/opal/PO-343_manualAccountCreation.feature
  cypress/support/step_definitions/manualAccountCreation/manualAccountCreation.ts
  src/app/app-routing.module.ts
  src/app/enums/routing-paths.ts
  src/app/pages/dashboard/dashboard.component.html
  src/app/pages/manual-account-creation/manual-account-creation.component.html
  src/app/pages/manual-account-creation/manual-account-creation.component.spec.ts
  src/app/pages/manual-account-creation/manual-account-creation.component.ts
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-481

#485 Po 274
  cypress/e2e/functional/opal/PO-343_manualAccountCreation.feature
  cypress/support/step_definitions/manualAccountCreation/manualAccountCreation.ts
  src/app/app-routing.module.ts
  src/app/app.component.html
  src/app/components/govuk/govuk-back-link/govuk-back-link.component.html
  src/app/components/govuk/govuk-back-link/govuk-back-link.component.spec.ts
  src/app/components/govuk/govuk-back-link/govuk-back-link.component.ts
  src/app/components/index.ts
  src/app/enums/routing-paths.ts
  src/app/pages/dashboard/dashboard.component.html
  src/app/pages/manual-account-creation/account-details/account-details.component.html
  src/app/pages/manual-account-creation/account-details/account-details.component.spec.ts
  src/app/pages/manual-account-creation/account-details/account-details.component.ts
  src/app/pages/manual-account-creation/manual-account-creation.component.html
  src/app/pages/manual-account-creation/manual-account-creation.component.ts
  src/styles.scss
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-485

#486 Po 279
  cypress/e2e/functional/opal/manualAccountCreation/PO-274_navigationLinksAndButtons.feature
  cypress/e2e/functional/opal/manualAccountCreation/PO-343_manualAccountCreation.feature
  cypress/e2e/functional/opal/manualAccountCreation/PO_279_adultAndYouthAcCreationPage.feature
  cypress/support/step_definitions/manualAccountCreation/manualAccountCreation.ts
  cypress/support/step_definitions/signInPage/signInTest.ts
  package.json
  src/app/app-routing.module.ts
  src/app/app.component.html
  src/app/components/govuk/govuk-back-link/govuk-back-link.component.spec.ts
  src/app/components/govuk/govuk-back-link/govuk-back-link.component.ts
  src/app/components/govuk/govuk-tag/govuk-tag.component.html
  src/app/components/govuk/govuk-tag/govuk-tag.component.spec.ts
  src/app/components/govuk/govuk-tag/govuk-tag.component.ts
  src/app/components/govuk/govuk-task-list/govuk-task-list-item/govuk-task-list-item.component.html
  src/app/components/govuk/govuk-task-list/govuk-task-list-item/govuk-task-list-item.component.spec.ts
  src/app/components/govuk/govuk-task-list/govuk-task-list-item/govuk-task-list-item.component.ts
  src/app/components/govuk/govuk-task-list/govuk-task-list.component.html
  src/app/components/govuk/govuk-task-list/govuk-task-list.component.spec.ts
  src/app/components/govuk/govuk-task-list/govuk-task-list.component.ts
  src/app/components/index.ts
  src/app/enums/index.ts
  src/app/enums/manual-account-creation-routes.ts
  src/app/enums/routing-paths.ts
  src/app/pages/account-enquiry/details/details.component.html
  src/app/pages/account-enquiry/matches/matches.component.html
  src/app/pages/account-enquiry/search/search-form/search-form.component.html
  src/app/pages/account-enquiry/search/search.component.html
  src/app/pages/dashboard/dashboard.component.html
  src/app/pages/dashboard/dashboard.component.ts
  src/app/pages/manual-account-creation/account-details/account-details.component.html
  src/app/pages/manual-account-creation/account-details/account-details.component.spec.ts
  src/app/pages/manual-account-creation/account-details/account-details.component.ts
  src/app/pages/manual-account-creation/create-account/create-account.component.html
  src/app/pages/manual-account-creation/create-account/create-account.component.spec.ts
  src/app/pages/manual-account-creation/create-account/create-account.component.ts
  src/app/pages/manual-account-creation/employer-details/employer-details.component.html
  src/app/pages/manual-account-creation/employer-details/employer-details.component.spec.ts
  src/app/pages/manual-account-creation/employer-details/employer-details.component.ts
  src/styles.scss
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-486

#510 Additional-components
  src/app/components/govuk/govuk-notification-banner/govuk-notification-banner.component.html
  src/app/components/govuk/govuk-notification-banner/govuk-notification-banner.component.spec.ts
  src/app/components/govuk/govuk-notification-banner/govuk-notification-banner.component.ts
  src/app/components/govuk/govuk-summary-card-list/govuk-summary-card-action/govuk-summary-card-action.component.html
  src/app/components/govuk/govuk-summary-card-list/govuk-summary-card-action/govuk-summary-card-action.component.spec.ts
  src/app/components/govuk/govuk-summary-card-list/govuk-summary-card-action/govuk-summary-card-action.component.ts
  src/app/components/govuk/govuk-summary-card-list/govuk-summary-card-list.component.html
  src/app/components/govuk/govuk-summary-card-list/govuk-summary-card-list.component.spec.ts
  src/app/components/govuk/govuk-summary-card-list/govuk-summary-card-list.component.ts
  src/app/components/govuk/govuk-text-input-prefix-suffix/govuk-text-input-prefix-suffix.component.html
  src/app/components/govuk/govuk-text-input-prefix-suffix/govuk-text-input-prefix-suffix.component.spec.ts
  src/app/components/govuk/govuk-text-input-prefix-suffix/govuk-text-input-prefix-suffix.component.ts
  src/app/components/index.ts
  src/app/components/moj/moj-banner/moj-banner.component.html
  src/app/components/moj/moj-banner/moj-banner.component.spec.ts
  src/app/components/moj/moj-banner/moj-banner.component.ts
  src/app/components/scotgov/scotgov-date-picker/scotgov-date-picker.component.html
  src/app/components/scotgov/scotgov-date-picker/scotgov-date-picker.component.spec.ts
  src/app/components/scotgov/scotgov-date-picker/scotgov-date-picker.component.ts
  src/app/pages/account-enquiry/search/search-form/search-form.component.html
  src/app/pages/account-enquiry/search/search-form/search-form.component.ts
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-510
