Repository hmcts/opal-frontend, pull requests merged in 2025-03, with the labels that each got.

#1272 Switch off sso on staging
  charts/opal-frontend/values.stg.template.yaml
  cypress/support/step_definitions/signInPage/signInTest.ts
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-1272

#1277 Revert "Switch off sso on staging"
  charts/opal-frontend/values.stg.template.yaml
  cypress/support/step_definitions/signInPage/signInTest.ts
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-1277

#1266 PO-1395
  cypress/e2e/functional/opal/manualAccountCreation/populateAndSubmit/pages/OffenceDetails.feature
  src/app/flows/fines/fines-mac/fines-mac-offence-details/fines-mac-offence-details-add-an-offence/fines-mac-offence-details-add-an-offence-form/fines-mac-offence-details-add-an-offence-form.component.ts
  src/app/flows/fines/fines-mac/fines-mac-offence-details/fines-mac-offence-details-add-an-offence/fines-mac-offence-details-add-an-offence.component.ts
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-1266

#1269 PO-1396
  cypress/e2e/functional/opal/manualAccountCreation/populateAndSubmit/pages/LanguagePreferences.feature
  src/app/flows/fines/fines-mac/routing/fines-mac.routes.ts
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-1269

#1292 Include Application Insights Domain in Helmet
  server/modules/helmet/index.ts
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-1292

#1293 Change helmet domain to look for
  server/modules/helmet/index.ts
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-1293

#1294 fix(cypress): update excludeSpecPattern to omit specific test directories
  cypress.config.ts
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-1294

#1295 Move component tests to after unit test stage
  Jenkinsfile_CNP
  cypress.config.ts
  cypress/component/manualAccountCreation/FinesMacOffenceDetails/AddOffence/AddOffence.cy.ts
  package.json
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-1295

#1313 Update Jenkinsfile_CNP
  Jenkinsfile_CNP
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-1313
