Repository hmcts/opal-frontend, pull requests merged in 2025-04, with the labels that each got.

#1179 Accessibility refactoring
  cypress/component/manualAccountCreation/FinesDraft/FinesDraftCreateAndManage/FinesDraftCreateAndManageComponent/FinesDraftCreateAndManageComponent.cy.ts
  cypress/component/manualAccountCreation/FinesDraft/FinesDraftCreateAndManage/FinesDraftCreateAndManageComponent/mocks/fines_draft_over_25_account_mock.ts
  cypress/parallel/weights/functional-parallel-weights.json
  cypress/parallel/weights/smoke-parallel-weights.json
  src/app/components/abstract/abstract-sortable-table/abstract-sortable-table.component.spec.ts
  src/app/components/abstract/abstract-sortable-table/abstract-sortable-table.component.ts
  src/app/components/abstract/abstract-sortable-table/interfaces/abstract-sortable-table-interfaces.ts
  src/app/components/abstract/abstract-sortable-table/types/abstract-sortable-table.type.ts
  src/app/components/govuk/govuk-pagination/govuk-pagination.component.html
  src/app/components/moj/moj-sortable-table/moj-sortable-table-header/moj-sortable-table-header.component.html
  src/app/components/moj/moj-sortable-table/moj-sortable-table-header/moj-sortable-table-header.component.spec.ts
  src/app/components/moj/moj-sortable-table/moj-sortable-table-header/moj-sortable-table-header.component.ts
  src/app/components/moj/moj-sortable-table/moj-sortable-table-status/moj-sortable-table-status.component.html
  src/app/components/moj/moj-sortable-table/moj-sortable-table-status/moj-sortable-table-status.component.spec.ts
  src/app/components/moj/moj-sortable-table/moj-sortable-table-status/moj-sortable-table-status.component.ts
  src/app/components/moj/moj-sortable-table/moj-sortable-table.component.html
  src/app/flows/fines/fines-draft/fines-draft-check-and-manage/fines-draft-check-and-manage-tabs/fines-draft-check-and-manage-tabs.component.spec.ts
  src/app/flows/fines/fines-draft/fines-draft-check-and-manage/fines-draft-check-and-manage-tabs/fines-draft-check-and-manage-tabs.component.ts
  src/app/flows/fines/fines-draft/fines-draft-table-wrapper/constants/fines-draft-table-wrapper-table-sort-default.constant.ts
  src/app/flows/fines/fines-draft/fines-draft-table-wrapper/fines-draft-table-wrapper.component.html
  src/app/flows/fines/fines-draft/fines-draft-table-wrapper/fines-draft-table-wrapper.component.ts
  src/app/flows/fines/fines-draft/fines-draft-table-wrapper/interfaces/fines-draft-table-wrapper-table-data.interface.ts
  src/app/flows/fines/fines-draft/fines-draft-table-wrapper/interfaces/fines-draft-table-wrapper-table-sort.interface.ts
  src/app/flows/fines/fines-draft/fines-draft-table-wrapper/mocks/fines-draft-table-wrapper-table-data.mock.ts
  src/app/pipes/date-format/date-format.pipe.spec.ts
  src/app/pipes/date-format/date-format.pipe.ts
  src/app/pipes/days-ago/days-ago.pipe.spec.ts
  src/app/pipes/days-ago/days-ago.pipe.ts
  src/app/services/date-service/date.service.spec.ts
  src/app/services/date-service/date.service.ts
  src/app/services/sort-service/interfaces/sort-service-values.ts
  src/app/services/sort-service/mocks/sort-service-object-input-mock.ts
  src/app/services/sort-service/types/sort-service-type.ts
  tsconfig.json
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-1179

#1246 PO-1289
  cypress/support/step_definitions/signInPage/signInTest.ts
  src/app/guards/auth/auth.guard.spec.ts
  src/app/guards/auth/auth.guard.ts
  src/app/pages/sign-in/sign-in-sso/sign-in-sso.component.html
  src/app/pages/sign-in/sign-in-sso/sign-in-sso.component.spec.ts
  src/app/pages/sign-in/sign-in-sso/sign-in-sso.component.ts
  src/app/pages/sign-in/sign-in.component.html
  src/app/pages/sign-in/sign-in.component.spec.ts
  src/app/pages/sign-in/sign-in.component.ts
Labels: ns:opal, prd:opal, stg/add-or-update, rel:opal-frontend-pr-1246

#1347 Descope smoke tests
  cypress/e2e/smoke/opal/PO-151_signOutTest.feature
  cypress/e2e/smoke/opal/PO-224_accessibilityTests.feature
  cypress/e2e/smoke/opal/signInTest.feature
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-1347

#1350 Setup frontend nightly
  Jenkinsfile_nightly
  package.json
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-1350

#1353 fix: update project name in Jenkinsfile_nightly for artifact operations
  Jenkinsfile_nightly
Labels: ns:opal, prd:opal

#1351 PO-1294
  .vscode/settings.json
  cypress/parallel/weights/functional-parallel-weights.json
  cypress/parallel/weights/smoke-parallel-weights.json
  multi-reporter-config.json
  package.json
  server-setup.ts
  server.ts
  server/api/index.ts
  server/api/opal-fines-service-proxy.ts
  server/api/proxy.ts
  server/csrf-token/csrf-token.ts
  server/csrf-token/index.ts
  server/global.d.ts
  server/interfaces/appInsightsConfig.ts
  server/interfaces/index.ts
  server/interfaces/launchDarklyConfig.ts
  server/interfaces/securityToken.ts
  server/interfaces/transferServerState.ts
  server/interfaces/userState.ts
  server/launch-darkly/index.ts
  server/launch-darkly/launch-darkly.ts
  server/modules/appinsights/app-insights-configuration.ts
  server/modules/appinsights/index.ts
  server/modules/health/index.ts
  server/modules/helmet/index.ts
  server/modules/index.ts
  server/modules/properties-volume/index.ts
  server/routes.ts
  server/session.d.ts
  server/session/expiry.ts
  server/session/index.ts
  server/session/session-storage.ts
  server/session/user-state.ts
  server/sso/index.ts
  server/sso/sso-authenticated.ts
  server/sso/sso-login-callback.ts
  server/sso/sso-login.ts
  server/sso/sso-logout-callback.ts
  server/sso/sso-logout.ts
  server/stubs/sso/index.ts
  server/stubs/sso/sso-authenticated.stub.ts
  server/stubs/sso/sso-login-callback.stub.ts
  server/stubs/sso/sso-login.stub.ts
  server/stubs/sso/sso-logout-callback.stub.ts
  server/stubs/sso/sso-logout.stub.ts
  server/type.d.ts
  server/utils/base64.ts
  server/utils/index.ts
  server/utils/jwt.ts
  tsconfig.server.json
  yarn.lock
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-1351

#1364 refactor(session): move sessionStorageConfig definition into configureSession function. Add temp console.log
  server-setup.ts
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-1364

#1366 Remove debug console log and update the config for application insights connection string as it was wrong
  server-setup.ts
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-1366

#1367 Use the correct value from config for the cloudRoleName for Application Insights
  server-setup.ts
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-1367

#1360 Fix Axe Issues on Check Account Details Screen
  cypress/e2e/functional/opal/manualAccountCreation/populateAndSubmit/PopulateAndSubmitAccessibility.feature
  cypress/support/step_definitions/accessibility/accessibility.ts
  src/app/flows/fines/fines-mac/fines-mac-review-account/fines-mac-review-account-account-comments-and-notes/fines-mac-review-account-account-comments-and-notes.component.html
  src/app/flows/fines/fines-mac/fines-mac-review-account/fines-mac-review-account-change-link/fines-mac-review-account-change-link.component.html
  src/app/flows/fines/fines-mac/fines-mac-review-account/fines-mac-review-account-change-link/fines-mac-review-account-change-link.component.ts
  src/app/flows/fines/fines-mac/fines-mac-review-account/fines-mac-review-account-company-details/fines-mac-review-account-company-details.component.html
  src/app/flows/fines/fines-mac/fines-mac-review-account/fines-mac-review-account-contact-details/fines-mac-review-account-contact-details.component.html
  src/app/flows/fines/fines-mac/fines-mac-review-account/fines-mac-review-account-court-details/fines-mac-review-account-court-details.component.html
  src/app/flows/fines/fines-mac/fines-mac-review-account/fines-mac-review-account-employer-details/fines-mac-review-account-employer-details.component.html
  src/app/flows/fines/fines-mac/fines-mac-review-account/fines-mac-review-account-offence-details/fines-mac-review-account-offence-details.component.html
  src/app/flows/fines/fines-mac/fines-mac-review-account/fines-mac-review-account-parent-guardian-details/fines-mac-review-account-parent-guardian-details.component.html
  src/app/flows/fines/fines-mac/fines-mac-review-account/fines-mac-review-account-payment-terms/fines-mac-review-account-payment-terms.component.html
  src/app/flows/fines/fines-mac/fines-mac-review-account/fines-mac-review-account-personal-details/fines-mac-review-account-personal-details.component.html
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-1360

#1380 correct properties in Jenkinsfile_nightly
  Jenkinsfile_nightly
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-1380

#1382 fix: update enforcement court name in CourtDetails.feature
  cypress/e2e/functional/opal/manualAccountCreation/populateAndSubmit/pages/CourtDetails.feature
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-1382
