Repository hmcts/opal-frontend, pull requests merged in 2025-08, with the labels that each got.

#1653 docs: add copilot instructions for Angular development best practices
  .github/copilot-instructions.md
  README.md
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-1653

#1621 Dev env support
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  charts/opal-frontend/Chart.yaml
  charts/opal-frontend/values.dev.template.yaml
  charts/opal-frontend/values.stg.template.yaml
  charts/opal-frontend/values.yaml
Labels: ns:opal, prd:opal, enable_keep_helm, enable_opal_fines_service, rel:opal-frontend-pr-1621

#1665 Made opal fines service defaulted to enabled
  Jenkinsfile_CNP
  charts/opal-frontend/values.dev.template.yaml
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-1665

#1666 Create mcp.json
  .vscode/mcp.json
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-1666

#1638 PO-1967
  angular.json
  cypress/component/manualAccountCreation/FinesDraft/FinesDraftCheckAndValidate/FinesDraftCheckAndValidate/CheckAndValidateDeleted.cy.ts
  cypress/component/manualAccountCreation/FinesDraft/FinesDraftCheckAndValidate/FinesDraftCheckAndValidate/CheckAndValidateFailed.cy.ts
  cypress/component/manualAccountCreation/FinesDraft/FinesDraftCheckAndValidate/FinesDraftCheckAndValidate/CheckAndValidateRejected.cy.ts
  cypress/component/manualAccountCreation/FinesDraft/FinesDraftCheckAndValidate/FinesDraftCheckAndValidate/CheckAndValidateToReview.cy.ts
  cypress/component/manualAccountCreation/FinesDraft/FinesDraftCheckAndValidate/FinesDraftCheckAndValidate/constants/fines_draft_cav_elements.ts
  cypress/component/manualAccountCreation/FinesDraft/FinesDraftCreateAndManage/FinesDraftCreateAndManageComponent/CreateAndManageApproved.cy.ts
  cypress/component/manualAccountCreation/FinesDraft/FinesDraftCreateAndManage/FinesDraftCreateAndManageComponent/CreateAndManageDeleted.cy.ts
  cypress/component/manualAccountCreation/FinesDraft/FinesDraftCreateAndManage/FinesDraftCreateAndManageComponent/CreateAndManageInReview.cy.ts
  cypress/component/manualAccountCreation/FinesDraft/FinesDraftCreateAndManage/FinesDraftCreateAndManageComponent/CreateAndManageRejected.cy.ts
  cypress/component/manualAccountCreation/FinesDraft/FinesDraftCreateAndManage/FinesDraftCreateAndManageComponent/FinesDraftViewAllRejected.cy.ts
  cypress/component/manualAccountCreation/FinesDraft/FinesDraftCreateAndManage/FinesDraftCreateAndManageComponent/constants/fines_draft_cam_inputter_elements.ts
  cypress/component/manualAccountCreation/FinesMacOffenceDetails/SearchOffenceResults/constants/search_offence_results_elements_mock.ts
  cypress/component/manualAccountCreation/FinesMacOffenceDetails/SearchOffenceResults/searchOffenceResults.cy.ts
  cypress/e2e/functional/opal/manualAccountCreation/populateAndSubmit/pages/OffenceDetails.feature
  src/app/flows/fines/components/fines-shared/fines-shared-sortable-table-footer/fines-shared-sortable-table-footer.component.html
  src/app/flows/fines/components/fines-shared/fines-shared-sortable-table-footer/fines-shared-sortable-table-footer.component.spec.ts
  src/app/flows/fines/components/fines-shared/fines-shared-sortable-table-footer/fines-shared-sortable-table-footer.component.ts
  src/app/flows/fines/fines-draft/fines-draft-table-wrapper/fines-draft-table-wrapper.component.html
  src/app/flows/fines/fines-draft/fines-draft-table-wrapper/fines-draft-table-wrapper.component.ts
  src/app/flows/fines/fines-mac/fines-mac-offence-details/fines-mac-offence-details-search-offences/fines-mac-offence-details-search-offences-results/fines-mac-offence-details-search-offences-results-table-wrapper/fines-mac-offence-details-search-offences-results-table-wrapper.component.html
  src/app/flows/fines/fines-mac/fines-mac-offence-details/fines-mac-offence-details-search-offences/fines-mac-offence-details-search-offences-results/fines-mac-offence-details-search-offences-results-table-wrapper/fines-mac-offence-details-search-offences-results-table-wrapper.component.ts
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-1638

#1669 enhance validation tests for the fields in FinesMacManualFixedPenalty
  cypress/component/manualAccountCreation/FinesFixedPenalty/FinesMacManualFixedPenalty/FinesMacManualFixedPenalty.cy.ts
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-1669

#1673 docs: add Copilot prompt examples for Angular MCP
  README.md
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-1673

#1672 PO-1990
  cypress/component/manualAccountCreation/FinesMacCourtDetails/FinesMacCourtDetails.cy.ts
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-1672

#1607 PO-1922
  .nvmrc
  cypress/component/manualAccountCreation/FinesFixedPenalty/FinesMacManualFixedPenalty/FinesMacManualFixedPenalty.cy.ts
  cypress/component/manualAccountCreation/FinesMacCompanyDetails/FinesMacCompanyDetails.cy.ts
  cypress/component/manualAccountCreation/FinesMacOffenceDetails/MinorCreditor/MinorCreditor.cy.ts
  cypress/component/manualAccountCreation/FinesMacParentGuardianDetails/FinesMacParentGuardianDetails.cy.ts
  cypress/e2e/Old_functional_E2E_Tests/manualAccountCreation/addOffence/minorCreditor/PO-412_minorCreditorAY.feature
  cypress/e2e/Old_functional_E2E_Tests/manualAccountCreation/addOffence/minorCreditor/PO-414_minorCreditorRemovalAY.feature
  cypress/e2e/Old_functional_E2E_Tests/manualAccountCreation/addOffence/minorCreditor/PO-668_minorCreditorAYPG.feature
  cypress/e2e/Old_functional_E2E_Tests/manualAccountCreation/addOffence/minorCreditor/PO-669_minorCreditorCOMP.feature
  cypress/e2e/Old_functional_E2E_Tests/manualAccountCreation/addOffence/minorCreditor/PO-670_minorCreditorRemovalAYPG.feature
  cypress/e2e/Old_functional_E2E_Tests/manualAccountCreation/addOffence/minorCreditor/PO-671_minorCreditorRemovalCOMP.feature
  cypress/e2e/Old_functional_E2E_Tests/manualAccountCreation/addOffence/minorCreditor/PO-686-minorCreditorEditAY.feature
  cypress/e2e/Old_functional_E2E_Tests/manualAccountCreation/addOffence/minorCreditor/PO-696_minorCreditorShowHide.feature
  cypress/e2e/functional/opal/manualAccountCreation/checkAndValidate/checkAndValidate.feature
  cypress/e2e/functional/opal/manualAccountCreation/fixedPenalty/fixedPenalty.feature
  cypress/e2e/functional/opal/manualAccountCreation/populateAndSubmit/PopulateAndSubmit.feature
  cypress/e2e/functional/opal/manualAccountCreation/populateAndSubmit/pages/OffenceDetails.feature
  cypress/e2e/functional/opal/manualAccountCreation/populateAndSubmit/pages/ParentGuardianDetails.feature
  cypress/support/step_definitions/manualAccountCreation/minorCreditorsTable.ts
  package.json
  src/app/flows/fines/constants/fines-patterns.constant.ts
  src/app/flows/fines/fines-mac/fines-mac-company-details/constants/fines-mac-company-details-alias.ts
  src/app/flows/fines/fines-mac/fines-mac-company-details/constants/fines-mac-company-details-field-errors.ts
  src/app/flows/fines/fines-mac/fines-mac-company-details/fines-mac-company-details-form/fines-mac-company-details-form.component.ts
  src/app/flows/fines/fines-mac/fines-mac-contact-details/fines-mac-contact-details-form/fines-mac-contact-details-form.component.ts
  src/app/flows/fines/fines-mac/fines-mac-court-details/constants/fines-mac-court-details-field-errors.ts
  src/app/flows/fines/fines-mac/fines-mac-court-details/fines-mac-court-details-form/fines-mac-court-details-form.component.ts
  src/app/flows/fines/fines-mac/fines-mac-delete-account-confirmation/constants/fines-mac-delete-account-confirmation-field-errors.constant.ts
  src/app/flows/fines/fines-mac/fines-mac-delete-account-confirmation/fines-mac-delete-account-confirmation-form/fines-mac-delete-account-confirmation-form.component.ts
  src/app/flows/fines/fines-mac/fines-mac-employer-details/constants/fines-mac-employer-details-field-errors.ts
  src/app/flows/fines/fines-mac/fines-mac-employer-details/fines-mac-employer-details-form/fines-mac-employer-details-form.component.ts
  src/app/flows/fines/fines-mac/fines-mac-fixed-penalty-details/constants/fines-mac-fixed-penalty-details-field-errors.ts
  src/app/flows/fines/fines-mac/fines-mac-fixed-penalty-details/constants/fines-mac-fixed-penalty-details-form-validators.ts
  src/app/flows/fines/fines-mac/fines-mac-fixed-penalty-details/fines-mac-fixed-penalty-details-form/fines-mac-fixed-penalty-details-form.component.ts
  src/app/flows/fines/fines-mac/fines-mac-offence-details/fines-mac-offence-details-add-an-offence/fines-mac-offence-details-add-an-offence-form/fines-mac-offence-details-add-an-offence-form.component.ts
  src/app/flows/fines/fines-mac/fines-mac-offence-details/fines-mac-offence-details-minor-creditor/constants/fines-mac-offence-details-minor-creditor-field-errors.constant.ts
  src/app/flows/fines/fines-mac/fines-mac-offence-details/fines-mac-offence-details-minor-creditor/fines-mac-offence-details-minor-creditor-form/fines-mac-offence-details-minor-creditor-form.component.spec.ts
  src/app/flows/fines/fines-mac/fines-mac-offence-details/fines-mac-offence-details-minor-creditor/fines-mac-offence-details-minor-creditor-form/fines-mac-offence-details-minor-creditor-form.component.ts
  src/app/flows/fines/fines-mac/fines-mac-offence-details/fines-mac-offence-details-search-offences/constants/fines-mac-offence-details-search-offences-errors.constant.ts
  src/app/flows/fines/fines-mac/fines-mac-offence-details/fines-mac-offence-details-search-offences/fines-mac-offence-details-search-offences-search/fines-mac-offence-details-search-offences-search-form/fines-mac-offence-details-search-offences-search-form.component.ts
  src/app/flows/fines/fines-mac/fines-mac-parent-guardian-details/constants/fines-mac-parent-guardian-details-alias.ts
  src/app/flows/fines/fines-mac/fines-mac-parent-guardian-details/fines-mac-parent-guardian-details-form/fines-mac-parent-guardian-details-form.component.ts
  src/app/flows/fines/fines-mac/fines-mac-payment-terms/constants/fines-mac-payment-terms-default-days-control-validation.ts
  src/app/flows/fines/fines-mac/fines-mac-payment-terms/constants/fines-mac-payment-terms-enforcement-action-options-control-validation.ts
  src/app/flows/fines/fines-mac/fines-mac-payment-terms/constants/fines-mac-payment-terms-field-errors.ts
  src/app/flows/fines/fines-mac/fines-mac-payment-terms/constants/fines-mac-payment-terms-instalments-only-control-validation.ts
  src/app/flows/fines/fines-mac/fines-mac-payment-terms/constants/fines-mac-payment-terms-lump-sum-control-validation.ts
  src/app/flows/fines/fines-mac/fines-mac-personal-details/constants/fines-mac-personal-details-alias.ts
  src/app/flows/fines/fines-mac/fines-mac-personal-details/fines-mac-personal-details-form/fines-mac-personal-details-form.component.ts
  src/app/flows/fines/fines-mac/fines-mac-review-account/fines-mac-review-account-decision/constants/fines-mac-review-account-decision-field-errors.constant.ts
  src/app/flows/fines/fines-mac/fines-mac-review-account/fines-mac-review-account-decision/fines-mac-review-account-decision-form/fines-mac-review-account-decision-form.component.spec.ts
  src/app/flows/fines/fines-mac/fines-mac-review-account/fines-mac-review-account-decision/fines-mac-review-account-decision-form/fines-mac-review-account-decision-form.component.ts
  src/app/flows/fines/fines-sa/fines-sa-search/fines-sa-search-account/fines-sa-search-account-form/fines-sa-search-account-form-companies/constants/fines-sa-search-account-form-companies-controls.constant.ts
  src/app/flows/fines/fines-sa/fines-sa-search/fines-sa-search-account/fines-sa-search-account-form/fines-sa-search-account-form-individuals/constants/fines-sa-search-account-form-individuals-controls.constant.ts
  src/app/flows/fines/fines-sa/fines-sa-search/fines-sa-search-account/fines-sa-search-account-form/fines-sa-search-account-form-minor-creditors/constants/fines-sa-search-account-form-minor-creditors-controls.constant.ts
  yarn.lock
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-1607

#1620 PO-717
  cypress/component/fineAccountEnquiry/searchAndMatches/SearchAndMatchesIndividuals.cy.ts
  cypress/component/fineAccountEnquiry/searchResults/SearchResultsIndividuals.cy.ts
  cypress/component/fineAccountEnquiry/searchResults/constants/search_results_individuals_elements.ts
  cypress/component/fineAccountEnquiry/searchResults/mocks/search_results_individuals_mock.ts
  cypress/component/fineAccountEnquiry/searchResults/mocks/search_results_sorting_mock.ts
  cypress/e2e/functional/opal/fineAccountEnquiry/searchAndMatches/searchAndMatches.feature
  cypress/support/step_definitions/searchAndMatches/searchAndMatches.ts
  src/app/flows/fines/constants/fines-default-values.constant.ts
  src/app/flows/fines/fines-mac/fines-mac-review-account/constants/fines-mac-review-account-default-values.constant.ts
  src/app/flows/fines/fines-mac/fines-mac-review-account/fines-mac-review-account-account-comments-and-notes/fines-mac-review-account-account-comments-and-notes.component.ts
  src/app/flows/fines/fines-mac/fines-mac-review-account/fines-mac-review-account-contact-details/fines-mac-review-account-contact-details.component.ts
  src/app/flows/fines/fines-mac/fines-mac-review-account/fines-mac-review-account-employer-details/fines-mac-review-account-employer-details.component.ts
  src/app/flows/fines/fines-mac/fines-mac-review-account/fines-mac-review-account-fixed-penalty-offence-details/fines-mac-review-account-fixed-penalty-offence-details.component.ts
  src/app/flows/fines/fines-mac/fines-mac-review-account/fines-mac-review-account-not-provided/fines-mac-review-account-not-provided.component.ts
  src/app/flows/fines/fines-mac/fines-mac-review-account/fines-mac-review-account-parent-guardian-details/fines-mac-review-account-parent-guardian-details.component.ts
  src/app/flows/fines/fines-mac/fines-mac-review-account/fines-mac-review-account-payment-terms/fines-mac-review-account-payment-terms.component.ts
  src/app/flows/fines/fines-mac/fines-mac-review-account/fines-mac-review-account-personal-details/fines-mac-review-account-personal-details.component.ts
  src/app/flows/fines/fines-sa/fines-sa-results/fines-sa-results-defendant-table-wrapper/constants/fines-sa-results-defendant-table-wrapper-table-sort-default.constant.ts
  src/app/flows/fines/fines-sa/fines-sa-results/fines-sa-results-defendant-table-wrapper/fines-sa-results-defendant-table-wrapper.component.html
  src/app/flows/fines/fines-sa/fines-sa-results/fines-sa-results-defendant-table-wrapper/fines-sa-results-defendant-table-wrapper.component.spec.ts
  src/app/flows/fines/fines-sa/fines-sa-results/fines-sa-results-defendant-table-wrapper/fines-sa-results-defendant-table-wrapper.component.ts
  src/app/flows/fines/fines-sa/fines-sa-results/fines-sa-results-defendant-table-wrapper/interfaces/fines-sa-results-defendant-table-wrapper-table-data.interface.ts
  src/app/flows/fines/fines-sa/fines-sa-results/fines-sa-results-defendant-table-wrapper/interfaces/fines-sa-results-defendant-table-wrapper-table-sort.interface.ts
  src/app/flows/fines/fines-sa/fines-sa-results/fines-sa-results-defendant-table-wrapper/mock/fines-sa-results-defendant-table-wrapper-table-data.mock.ts
  src/app/flows/fines/fines-sa/fines-sa-results/fines-sa-results-minor-creditor-table-wrapper/fines-sa-results-minor-creditor-table-wrapper.component.html
  src/app/flows/fines/fines-sa/fines-sa-results/fines-sa-results-minor-creditor-table-wrapper/fines-sa-results-minor-creditor-table-wrapper.component.spec.ts
  src/app/flows/fines/fines-sa/fines-sa-results/fines-sa-results-minor-creditor-table-wrapper/fines-sa-results-minor-creditor-table-wrapper.component.ts
  src/app/flows/fines/fines-sa/fines-sa-results/fines-sa-results.component.html
  src/app/flows/fines/fines-sa/fines-sa-results/fines-sa-results.component.spec.ts
  src/app/flows/fines/fines-sa/fines-sa-results/fines-sa-results.component.ts
  src/app/flows/fines/fines-sa/fines-sa-results/types/fines-sa-results-tabs.type.ts
  src/app/flows/fines/fines-sa/fines-sa-search/fines-sa-search-account/fines-sa-search-account-form/fines-sa-search-account-form-companies/mocks/fines-sa-search-account-form-companies-state.mock.ts
  src/app/flows/fines/fines-sa/fines-sa-search/fines-sa-search-account/fines-sa-search-account-form/fines-sa-search-account-form-minor-creditors/mocks/fines-sa-search-account-form-minor-creditors-state.mock.ts
  src/app/flows/fines/fines-sa/fines-sa-search/fines-sa-search-account/fines-sa-search-account-form/fines-sa-search-account-form.component.ts
  src/app/flows/fines/fines-sa/fines-sa-search/fines-sa-search-account/types/fines-sa-search-account-tab.type.ts
  src/app/flows/fines/fines-sa/fines-sa-search/fines-sa-search-account/types/fines-sa-search-account-tabs.type.ts
  src/app/flows/fines/fines-sa/fines-sa-search/routing/fines-sa-search.routes.ts
  src/app/flows/fines/fines-sa/routing/fines-sa.routes.ts
  src/app/flows/fines/fines-sa/routing/resolvers/fines-sa-individual-accounts.resolver.spec.ts
  src/app/flows/fines/fines-sa/routing/resolvers/fines-sa-individual-accounts.resolver.ts
  src/app/flows/fines/fines-sa/services/fines-sa.service.spec.ts
  src/app/flows/fines/fines-sa/services/fines-sa.service.ts
  src/app/flows/fines/fines-sa/stores/fines-sa.store.ts
  src/app/flows/fines/interfaces/fines-default-values.interface.ts
  src/app/flows/fines/services/opal-fines-service/constants/opal-fines-defendant-account-search-params-defaults.constant.ts
  src/app/flows/fines/services/opal-fines-service/constants/opal-fines-paths.constant.ts
  src/app/flows/fines/services/opal-fines-service/interfaces/opal-fines-defendant-account.interface.ts
  src/app/flows/fines/services/opal-fines-service/interfaces/opal-fines-defendant-acount-search-params.interface.ts
  src/app/flows/fines/services/opal-fines-service/interfaces/opal-fines-paths.interface.ts
  src/app/flows/fines/services/opal-fines-service/mocks/opal-fines-defendant-account-response-individual.mock.ts
  src/app/flows/fines/services/opal-fines-service/opal-fines.service.spec.ts
  src/app/flows/fines/services/opal-fines-service/opal-fines.service.ts
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-1620

#1719 Update tabs to use moj-notification-badge component for number indicator
  src/app/flows/fines/fines-draft/fines-draft-check-and-validate/fines-draft-check-and-validate-tabs/fines-draft-check-and-validate-tabs.component.html
  src/app/flows/fines/fines-draft/fines-draft-check-and-validate/fines-draft-check-and-validate-tabs/fines-draft-check-and-validate-tabs.component.ts
  src/app/flows/fines/fines-draft/fines-draft-create-and-manage/fines-draft-create-and-manage-tabs/fines-draft-create-and-manage-tabs.component.html
  src/app/flows/fines/fines-draft/fines-draft-create-and-manage/fines-draft-create-and-manage-tabs/fines-draft-create-and-manage-tabs.component.ts
Labels: ns:opal, prd:opal, skip_opal_component, rel:opal-frontend-pr-1719

#1661 PO-1998
  cypress/component/fineAccountEnquiry/searchAndMatches/SearchAndMatchesIndividuals.cy.ts
  cypress/component/fineAccountEnquiry/searchAndMatches/constants/search_and_matches_individuals_elements.ts
  cypress/support/utils/dateUtils.ts
  src/app/flows/fines/fines-sa/fines-sa-search/fines-sa-search-account/fines-sa-search-account-form/fines-sa-search-account-form-individuals/fines-sa-search-account-form-individuals.component.html
  src/app/flows/fines/fines-sa/fines-sa-search/fines-sa-search-account/fines-sa-search-account-form/fines-sa-search-account-form-individuals/fines-sa-search-account-form-individuals.component.spec.ts
  src/app/flows/fines/fines-sa/fines-sa-search/fines-sa-search-account/fines-sa-search-account-form/fines-sa-search-account-form-individuals/fines-sa-search-account-form-individuals.component.ts
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-1661
