Repository hmcts/opal-frontend, pull requests merged in 2025-01, with the labels that each got.

#1138 Refactor payload mapping to remove unnecessary null checks
  src/app/flows/fines/fines-mac/services/fines-mac-payload/utils/fines-mac-payload-map-account/fines-mac-payload-map-account-defendant-company.utils.ts
  src/app/flows/fines/fines-mac/services/fines-mac-payload/utils/fines-mac-payload-map-account/fines-mac-payload-map-account-defendant-individual.utils.ts
  src/app/flows/fines/fines-mac/services/fines-mac-payload/utils/fines-mac-payload-map-account/fines-mac-payload-map-account-defendant-parent-guardian.utils.ts
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-1138

#1140 Payload unit tests 2
  src/app/flows/fines/fines-mac/services/fines-mac-payload/fines-mac-payload.service.spec.ts
  src/app/flows/fines/fines-mac/services/fines-mac-payload/utils/fines-mac-payload-map-account/fines-mac-payload-map-account-defendant-company.utils.spec.ts
  src/app/flows/fines/fines-mac/services/fines-mac-payload/utils/fines-mac-payload-map-account/fines-mac-payload-map-account-defendant-company.utils.ts
  src/app/flows/fines/fines-mac/services/fines-mac-payload/utils/fines-mac-payload-map-account/fines-mac-payload-map-account-defendant-individual.utils.spec.ts
  src/app/flows/fines/fines-mac/services/fines-mac-payload/utils/fines-mac-payload-map-account/fines-mac-payload-map-account-defendant-individual.utils.ts
  src/app/flows/fines/fines-mac/services/fines-mac-payload/utils/fines-mac-payload-map-account/fines-mac-payload-map-account-defendant-parent-guardian.utils.spec.ts
  src/app/flows/fines/fines-mac/services/fines-mac-payload/utils/fines-mac-payload-map-account/fines-mac-payload-map-account-defendant-parent-guardian.utils.ts
  src/app/flows/fines/fines-mac/services/fines-mac-payload/utils/fines-mac-payload-map-account/fines-mac-payload-map-account-offences.utils.spec.ts
  src/app/flows/fines/fines-mac/services/fines-mac-payload/utils/fines-mac-payload-map-account/fines-mac-payload-map-account-offences.utils.ts
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-1140

#1141 Delete unused files to prevent 0% coverage being reported
  src/app/flows/fines/fines-mac/constants/controls/fines-mac-controls-add-alias.ts
  src/app/flows/fines/fines-mac/constants/controls/fines-mac-controls-address-line-one.ts
  src/app/flows/fines/fines-mac/constants/controls/fines-mac-controls-address-line-two.ts
  src/app/flows/fines/fines-mac/constants/controls/fines-mac-controls-aliases.ts
  src/app/flows/fines/fines-mac/constants/controls/fines-mac-controls-dob.ts
  src/app/flows/fines/fines-mac/constants/controls/fines-mac-controls-forenames.ts
  src/app/flows/fines/fines-mac/constants/controls/fines-mac-controls-national-insurance-number.ts
  src/app/flows/fines/fines-mac/constants/controls/fines-mac-controls-postcode.ts
  src/app/flows/fines/fines-mac/constants/controls/fines-mac-controls-surname.ts
  src/app/flows/fines/fines-mac/constants/controls/fines-mac-controls-vehicle-make.ts
  src/app/flows/fines/fines-mac/constants/controls/fines-mac-controls-vehicle-registration-mark.ts
  src/app/flows/fines/fines-mac/fines-mac-offence-details/fines-mac-offence-details-add-an-offence/fines-mac-offence-details-add-an-offence-form/mocks/fines-mac-offence-details-add-an-offence-form-minor-creditor.mocks.ts
  src/app/flows/fines/fines-mac/fines-mac-offence-details/fines-mac-offence-details-minor-creditor/constants/fines-mac-offence-details-minor-creditor-form.constant.ts
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-1141

#1130 Govuk test optimisation
  src/app/components/alphagov/alphagov-accessible-autocomplete/alphagov-accessible-autocomplete.component.spec.ts
  src/app/components/govuk/govuk-accordion/govuk-accordion.component.spec.ts
  src/app/components/govuk/govuk-back-link/govuk-back-link.component.spec.ts
  src/app/components/govuk/govuk-button/govuk-button.component.spec.ts
  src/app/components/govuk/govuk-cancel-link/govuk-cancel-link.component.spec.ts
  src/app/components/govuk/govuk-checkboxes/govuk-checkboxes-conditional/govuk-checkboxes-conditional.component.spec.ts
  src/app/components/govuk/govuk-checkboxes/govuk-checkboxes-divider/govuk-checkboxes-divider.component.spec.ts
  src/app/components/govuk/govuk-checkboxes/govuk-checkboxes-item/govuk-checkboxes-item.component.spec.ts
  src/app/components/govuk/govuk-checkboxes/govuk-checkboxes.component.spec.ts
  src/app/components/govuk/govuk-date-input/govuk-date-input.component.spec.ts
  src/app/components/govuk/govuk-details/govuk-details.component.spec.ts
  src/app/components/govuk/govuk-error-summary/govuk-error-summary.component.spec.ts
  src/app/components/govuk/govuk-footer/govuk-footer.component.spec.ts
  src/app/components/govuk/govuk-header/govuk-header-navigation-item/govuk-header-navigation-item.component.spec.ts
  src/app/components/govuk/govuk-header/govuk-header.component.spec.ts
  src/app/components/govuk/govuk-heading-with-caption/govuk-heading-with-caption.component.spec.ts
  src/app/components/govuk/govuk-inset-text/govuk-inset-text.component.spec.ts
  src/app/components/govuk/govuk-notification-banner/govuk-notification-banner.component.spec.ts
  src/app/components/govuk/govuk-pagination/govuk-pagination.component.spec.ts
  src/app/components/govuk/govuk-panel/govuk-panel.component.spec.ts
  src/app/components/govuk/govuk-radio/govuk-radio.component.spec.ts
  src/app/components/govuk/govuk-radio/govuk-radios-conditional/govuk-radios-conditional.component.spec.ts
  src/app/components/govuk/govuk-radio/govuk-radios-divider/govuk-radios-divider.component.spec.ts
  src/app/components/govuk/govuk-radio/govuk-radios-item/govuk-radios-item.component.spec.ts
  src/app/components/govuk/govuk-select/govuk-select.component.spec.ts
  src/app/components/govuk/govuk-summary-card-list/govuk-summary-card-action/govuk-summary-card-action.component.spec.ts
  src/app/components/govuk/govuk-summary-card-list/govuk-summary-card-list.component.spec.ts
  src/app/components/govuk/govuk-summary-list/govuk-summary-list-row/govuk-summary-list-row.component.spec.ts
  src/app/components/govuk/govuk-summary-list/govuk-summary-list.component.spec.ts
  src/app/components/govuk/govuk-table/govuk-table-body-row/govuk-table-body-row-data/govuk-table-body-row-data.component.spec.ts
  src/app/components/govuk/govuk-table/govuk-table-body-row/govuk-table-body-row.component.spec.ts
  src/app/components/govuk/govuk-table/govuk-table-heading/govuk-table-heading.component.spec.ts
  src/app/components/govuk/govuk-table/govuk-table.component.spec.ts
  src/app/components/govuk/govuk-tabs/govuk-tab-list-item/govuk-tab-list-item.component.spec.ts
  src/app/components/govuk/govuk-tabs/govuk-tab-panel/govuk-tab-panel.component.spec.ts
  src/app/components/govuk/govuk-tabs/govuk-tabs.component.spec.ts
  src/app/components/govuk/govuk-tag/govuk-tag.component.spec.ts
  src/app/components/govuk/govuk-task-list/govuk-task-list-item/govuk-task-list-item.component.spec.ts
  src/app/components/govuk/govuk-task-list/govuk-task-list.component.spec.ts
  src/app/components/govuk/govuk-text-area/govuk-text-area.component.spec.ts
  src/app/components/govuk/govuk-text-input-prefix-suffix/govuk-text-input-prefix-suffix.component.spec.ts
  src/app/components/govuk/govuk-text-input/govuk-text-input.component.spec.ts
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-1130

#1145 fix: set parent_guardian to null in fines mac payload service and mocks
  src/app/flows/fines/fines-mac/services/fines-mac-payload/fines-mac-payload.service.spec.ts
  src/app/flows/fines/fines-mac/services/fines-mac-payload/utils/fines-mac-payload-build-account/fines-mac-payload-build-account-defendant.utils.ts
  src/app/flows/fines/fines-mac/services/fines-mac-payload/utils/mocks/fines-mac-payload-account-defendant-company-complete-with-aliases.mock.ts
  src/app/flows/fines/fines-mac/services/fines-mac-payload/utils/mocks/fines-mac-payload-account-defendant-company-complete.mock.ts
  src/app/flows/fines/fines-mac/services/fines-mac-payload/utils/mocks/fines-mac-payload-account-defendant-individual-complete-with-alias.mock.ts
  src/app/flows/fines/fines-mac/services/fines-mac-payload/utils/mocks/fines-mac-payload-account-defendant-individual-complete.mock.ts
  src/app/flows/fines/fines-mac/services/fines-mac-payload/utils/mocks/fines-mac-payload-account-defendant-parent-guardian-complete-with-alias.mock.ts
  src/app/flows/fines/fines-mac/services/fines-mac-payload/utils/mocks/fines-mac-payload-account-defendant-parent-guardian-complete.mock.ts
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-1145

#1143 Mapping tidy 2
  src/app/flows/fines/fines-mac/services/fines-mac-payload/utils/fines-mac-payload-build-account/fines-mac-payload-build-account-offences.utils.ts
  src/app/flows/fines/fines-mac/services/fines-mac-payload/utils/fines-mac-payload-map-account/fines-mac-payload-map-account-defendant-parent-guardian.utils.ts
  src/app/flows/fines/fines-mac/services/fines-mac-payload/utils/fines-mac-payload-map-account/fines-mac-payload-map-account-payment-terms.utils.ts
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-1143

#1103 PO-982
  cypress/e2e/functional/opal/manualAccountCreation/accountCreationPage/PO_279_adultAndYouthAcCreationPage.feature
  cypress/e2e/functional/opal/manualAccountCreation/accountDetails/PO-362_companyTaskList.feature
  cypress/e2e/functional/opal/manualAccountCreation/accountDetails/PO-366_updateAccountDetails.feature
  cypress/e2e/functional/opal/manualAccountCreation/accountDetails/PO-367_accountCreation_parentOrGuardian.feature
  cypress/e2e/functional/opal/manualAccountCreation/accountDetails/PO-443_reorderingAccountDetails.feature
  cypress/e2e/functional/opal/manualAccountCreation/accountDetails/PO-549_reviewAccountButtonEnabledAY.feature
  cypress/e2e/functional/opal/manualAccountCreation/accountDetails/PO-653_reviewAccountButtonEnabledAYPG.feature
  cypress/e2e/functional/opal/manualAccountCreation/accountDetails/PO-654_reviewAccountButtonEnabledCOMP.feature
  cypress/e2e/functional/opal/manualAccountCreation/checkAccountDetails/PO-560_checkAccountDetailsAY.feature
  cypress/e2e/functional/opal/manualAccountCreation/checkAccountDetails/PO-662_checkAccountDetailsAYPG.feature
  cypress/e2e/functional/opal/manualAccountCreation/checkAccountDetails/PO-663_checkAccountDetailsCOMP.feature
  src/app/flows/fines/fines-mac/fines-mac-account-details/fines-mac-account-details.component.html
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-1103

#1148 PO-1055
  src/app/pages/sign-in/sign-in-stub/sign-in-stub.component.html
  src/styles.scss
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-1148

#1157 Update Chart.yaml
  charts/opal-frontend/Chart.yaml
Labels: ns:opal, prd:opal

#1158 PO-640 - Refactor
  src/app/flows/fines/fines-mac/fines-mac-account-details/fines-mac-account-details.component.html
  src/app/flows/fines/fines-mac/fines-mac-account-details/fines-mac-account-details.component.spec.ts
  src/app/flows/fines/fines-mac/fines-mac-account-details/fines-mac-account-details.component.ts
  src/app/flows/fines/fines-mac/fines-mac-review-account/fines-mac-review-account.component.html
  src/app/flows/fines/fines-mac/fines-mac-review-account/fines-mac-review-account.component.spec.ts
  src/app/flows/fines/fines-mac/fines-mac-review-account/fines-mac-review-account.component.ts
  src/app/flows/fines/fines-mac/routing/fines-mac.routes.ts
  src/app/flows/fines/fines-mac/routing/resolvers/draft-account-resolver/interfaces/draft-account-resolver.interface.ts
  src/app/flows/fines/fines-mac/routing/resolvers/draft-account-resolver/mocks/draft-account-resolver.mock.ts
  src/app/flows/fines/fines-mac/routing/resolvers/fetch-map-fines-mac-payload-resolver/fetch-map-fines-mac-payload.resolver.spec.ts
  src/app/flows/fines/fines-mac/routing/resolvers/fetch-map-fines-mac-payload-resolver/fetch-map-fines-mac-payload.resolver.ts
  src/app/flows/fines/fines-mac/routing/resolvers/fetch-map-fines-mac-payload-resolver/interfaces/fetch-map-fines-mac-payload.interface.ts
  src/app/flows/fines/fines-mac/services/fines-mac-payload/fines-mac-payload.service.spec.ts
  src/app/flows/fines/fines-mac/services/fines-mac-payload/fines-mac-payload.service.ts
  src/app/flows/fines/fines-mac/services/fines-mac-payload/utils/fines-mac-payload-map-account/fines-mac-payload-map-account-offences.utils.spec.ts
  src/app/flows/fines/fines-mac/services/fines-mac-payload/utils/fines-mac-payload-map-account/fines-mac-payload-map-account-offences.utils.ts
  src/app/flows/fines/fines-mac/services/fines-mac-payload/utils/fines-mac-payload-map-account/fines-mac-payload-map-business-unit.utils.spec.ts
  src/app/flows/fines/fines-mac/services/fines-mac-payload/utils/fines-mac-payload-map-account/fines-mac-payload-map-business-unit.utils.ts
Labels: ns:opal, prd:opal

#1175 refactor: remove unused interfaces and mock data from opal fines service
  src/app/flows/fines/services/opal-fines-service/constants/opal-fines-paths.constant.ts
  src/app/flows/fines/services/opal-fines-service/interfaces/opal-fines-add-defendant-account-note-body.interface.ts
  src/app/flows/fines/services/opal-fines-service/interfaces/opal-fines-defendant-account-details.interface.ts
  src/app/flows/fines/services/opal-fines-service/interfaces/opal-fines-defendant-account-note.interface.ts
  src/app/flows/fines/services/opal-fines-service/interfaces/opal-fines-defendant-account.interface.ts
  src/app/flows/fines/services/opal-fines-service/interfaces/opal-fines-get-defendant-account-params.interface.ts
  src/app/flows/fines/services/opal-fines-service/interfaces/opal-fines-paths.interface.ts
  src/app/flows/fines/services/opal-fines-service/interfaces/opal-fines-search-court-body.interface.ts
  src/app/flows/fines/services/opal-fines-service/interfaces/opal-fines-search-court.interface.ts
  src/app/flows/fines/services/opal-fines-service/interfaces/opal-fines-search-defendant-account-body.interface.ts
  src/app/flows/fines/services/opal-fines-service/interfaces/opal-fines-search-defendant-accounts.interface.ts
  src/app/flows/fines/services/opal-fines-service/mocks/opal-fines-add-defendant-account-note.mock.ts
  src/app/flows/fines/services/opal-fines-service/mocks/opal-fines-defendant-account-details.mock.ts
  src/app/flows/fines/services/opal-fines-service/mocks/opal-fines-defendant-account-note.mock.ts
  src/app/flows/fines/services/opal-fines-service/mocks/opal-fines-defendant-account-notes.mock.ts
  src/app/flows/fines/services/opal-fines-service/mocks/opal-fines-defendant-account.mock.ts
  src/app/flows/fines/services/opal-fines-service/mocks/opal-fines-search-court-body.mock.ts
  src/app/flows/fines/services/opal-fines-service/mocks/opal-fines-search-court.mock.ts
  src/app/flows/fines/services/opal-fines-service/mocks/opal-fines-search-defendant-accounts.mock.ts
  src/app/flows/fines/services/opal-fines-service/opal-fines.service.spec.ts
  src/app/flows/fines/services/opal-fines-service/opal-fines.service.ts
Labels: ns:opal, prd:opal

#1188 fix(deps): downgrade applicationinsights to version ~2.9.6
  package.json
  yarn.lock
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-1188

#1192 Revert "fix(deps): update dependency applicationinsights to v3"
  package.json
  yarn.lock
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-1192
