Repository hmcts/opal-frontend, pull requests merged in 2025-02, with the labels that each got.

#1171 PO-1156 - NgRx Signal Store
  cypress/parallel/weights/smoke-parallel-weights.json
  package.json
  src/app/app.component.html
  src/app/app.component.spec.ts
  src/app/app.component.ts
  src/app/components/abstract/abstract-form-base/abstract-form-base.component.ts
  src/app/components/abstract/abstract-form-parent-base/abstract-form-parent-base.component.ts
  src/app/components/govuk/govuk-header/govuk-header.component.ts
  src/app/flows/fines/fines-mac/fines-mac-offence-details/fines-mac-offence-details.component.spec.ts
  src/app/flows/fines/fines-mac/fines-mac-offence-details/fines-mac-offence-details.component.ts
  src/app/flows/fines/fines-mac/fines-mac-payment-terms/fines-mac-payment-terms-form/fines-mac-payment-terms-form.component.spec.ts
  src/app/flows/fines/fines-mac/fines-mac-payment-terms/fines-mac-payment-terms-form/fines-mac-payment-terms-form.component.ts
  src/app/flows/fines/fines-mac/fines-mac-review-account/fines-mac-review-account-payment-terms/fines-mac-review-account-payment-terms.component.spec.ts
  src/app/flows/fines/fines-mac/fines-mac-review-account/fines-mac-review-account-payment-terms/fines-mac-review-account-payment-terms.component.ts
  src/app/flows/fines/fines-mac/fines-mac-review-account/fines-mac-review-account.component.spec.ts
  src/app/flows/fines/fines-mac/fines-mac-review-account/fines-mac-review-account.component.ts
  src/app/flows/fines/fines-mac/fines-mac-submit-confirmation/fines-mac-submit-confirmation.component.spec.ts
  src/app/flows/fines/fines-mac/fines-mac.component.spec.ts
  src/app/flows/fines/fines-mac/fines-mac.component.ts
  src/app/flows/fines/fines.component.spec.ts
  src/app/flows/fines/fines.component.ts
  src/app/guards/auth/auth.guard.spec.ts
  src/app/interceptors/http-error/http-error.interceptor.spec.ts
  src/app/interceptors/http-error/http-error.interceptor.ts
  src/app/pages/dashboard/dashboard.component.html
  src/app/pages/dashboard/dashboard.component.ts
  src/app/pages/sign-in/sign-in.component.spec.ts
  src/app/pages/sign-in/sign-in.component.ts
  src/app/services/auth-service/auth.service.spec.ts
  src/app/services/auth-service/auth.service.ts
  src/app/services/global-state-service/global-state.service.spec.ts
  src/app/services/global-state-service/global-state.service.ts
  src/app/services/launch-darkly/launch-darkly.service.spec.ts
  src/app/services/launch-darkly/launch-darkly.service.ts
  src/app/services/session-service/session.service.spec.ts
  src/app/services/session-service/session.service.ts
  src/app/services/transfer-state-service/transfer-state.service.spec.ts
  src/app/services/transfer-state-service/transfer-state.service.ts
  src/app/stores/global/global.store.spec.ts
  src/app/stores/global/global.store.ts
  src/app/stores/global/interfaces/error-state.interface.ts
  src/app/stores/global/types/global-store.type.ts
  tsconfig.json
  yarn.lock
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-1171

#1204 Fix Sign in/Sign out links
  src/app/components/moj/moj-header/moj-header-navigation-item/moj-header-navigation-item.component.html
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-1204

#1220 fix: Exclude mock files from SonarCloud
  sonar-project.properties
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-1220

#1226 PO-1275
  src/app/components/abstract/abstract-form-base/abstract-form-base.component.spec.ts
  src/app/components/abstract/abstract-form-base/abstract-form-base.component.ts
  yarn-audit-known-issues
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-1226

#1232 Fix Sonar Issue
  src/app/flows/fines/fines-mac/fines-mac-offence-details/fines-mac-offence-details-add-an-offence/fines-mac-offence-details-add-an-offence-form/fines-mac-offence-details-add-an-offence-form.component.ts
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-1232

#1235 Cookie Change Test
  charts/opal-frontend/Chart.yaml
  charts/opal-frontend/values.stg.template.yaml
  charts/opal-frontend/values.yaml
  config/custom-environment-variables.json
  config/default.json
  server/session/session-storage.ts
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-1235

#1207 PO-1170
  charts/opal-frontend/Chart.yaml
  charts/opal-frontend/values.dev.template.yaml
  charts/opal-frontend/values.stg.template.yaml
  charts/opal-frontend/values.yaml
  config/custom-environment-variables.json
  config/default.json
  package.json
  server.ts
  server/interfaces/appInsightsConfig.ts
  server/interfaces/index.ts
  server/interfaces/transferServerState.ts
  server/modules/appinsights/app-insights-configuration.ts
  server/modules/appinsights/index.ts
  src/app/app.component.spec.ts
  src/app/app.component.ts
  src/app/app.config.ts
  src/app/interceptors/http-error/http-error.interceptor.ts
  src/app/services/app-insights/app-insights.service.spec.ts
  src/app/services/app-insights/app-insights.service.ts
  src/app/services/transfer-state-service/interfaces/transfer-state-app-insights-config.interface.ts
  src/app/services/transfer-state-service/interfaces/transfer-state-server-state.interface.ts
  src/app/services/transfer-state-service/mocks/transfer-state-app-insights-config.mock.ts
  src/app/services/transfer-state-service/mocks/transfer-state.mock.ts
  yarn.lock
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-1207
