Repository hmcts/opal-frontend, pull requests merged in 2025-07, with the labels that each got.

#1570 PO-1903
  cypress/component/manualAccountCreation/FinesMacOffenceDetails/SearchOffenceResults/mocks/offence_search_results_mock.ts
  package.json
  src/app/flows/fines/fines-mac/fines-mac-offence-details/fines-mac-offence-details-search-offences/fines-mac-offence-details-search-offences-results/fines-mac-offence-details-search-offences-results-table-wrapper/fines-mac-offence-details-search-offences-results-table-wrapper.component.ts
  src/app/flows/fines/fines-mac/fines-mac-offence-details/fines-mac-offence-details-search-offences/routing/resolvers/fines-mac-offence-details-search-offences.resolver.spec.ts
  src/app/flows/fines/fines-mac/fines-mac-offence-details/fines-mac-offence-details-search-offences/routing/resolvers/fines-mac-offence-details-search-offences.resolver.ts
  src/app/flows/fines/services/opal-fines-service/interfaces/opal-fines-search-offences-params.interface.ts
  src/app/flows/fines/services/opal-fines-service/mocks/opal-fines-search-offences-params.mock.ts
  src/app/flows/fines/services/opal-fines-service/opal-fines.service.ts
  yarn.lock
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-1570

#1568 Update README.md
  README.md
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-1568

#1578 PO-836: MoJ Filter Abstract Classes Changes
  multi-reporter-config.json
  package.json
  src/app/flows/fines/components/fines-shared/fines-shared-sortable-table-footer/fines-shared-sortable-table-footer.component.html
  src/app/flows/fines/components/fines-shared/fines-shared-sortable-table-footer/fines-shared-sortable-table-footer.component.ts
  src/app/flows/fines/fines-draft/fines-draft-table-wrapper/fines-draft-table-wrapper.component.html
  src/app/flows/fines/fines-draft/fines-draft-table-wrapper/fines-draft-table-wrapper.component.spec.ts
  src/app/flows/fines/fines-draft/fines-draft-table-wrapper/fines-draft-table-wrapper.component.ts
  src/app/flows/fines/fines-mac/fines-mac-offence-details/fines-mac-offence-details-search-offences/fines-mac-offence-details-search-offences-results/fines-mac-offence-details-search-offences-results-table-wrapper/fines-mac-offence-details-search-offences-results-table-wrapper.component.html
  src/app/flows/fines/fines-mac/fines-mac-offence-details/fines-mac-offence-details-search-offences/fines-mac-offence-details-search-offences-results/fines-mac-offence-details-search-offences-results-table-wrapper/fines-mac-offence-details-search-offences-results-table-wrapper.component.ts
  yarn.lock
Labels: ns:opal, prd:opal, skip_opal_component, rel:opal-frontend-pr-1578

#1573 PO-712
  cypress/component/fineAccountEnquiry/searchAndMatches/SearchAndMatchesCompany.cy.ts
  cypress/component/fineAccountEnquiry/searchAndMatches/constants/search_and_matches_company_elements.ts
  cypress/component/fineAccountEnquiry/searchAndMatches/mocks/search_and_matches_company_mock.ts
  cypress/component/manualAccountCreation/FinesDraft/FinesDraftCheckAndValidate/FinesDraftCheckAndValidate/CheckAndValidateRejected.cy.ts
  cypress/component/manualAccountCreation/FinesDraft/FinesDraftCheckAndValidate/FinesDraftCheckAndValidate/mocks/fines-draft-validate-account.mock.ts
  cypress/component/manualAccountCreation/FinesDraft/FinesDraftCheckAndValidate/FinesDraftCheckAndValidate/mocks/fines-draft-validate-delete-account.mock.ts
  cypress/component/manualAccountCreation/FinesDraft/FinesDraftCheckAndValidate/FinesDraftCheckAndValidate/mocks/fines_draft_validate_over_25_account_mock.ts
  cypress/component/manualAccountCreation/FinesDraft/FinesDraftCreateAndManage/FinesDraftCreateAndManageComponent/mocks/fines-draft-delete-account.mock.ts
  cypress/component/manualAccountCreation/FinesDraft/FinesDraftCreateAndManage/FinesDraftCreateAndManageComponent/mocks/fines_draft_over_25_account_mock.ts
  cypress/component/manualAccountCreation/FinesMacAccountCommentsAndNotes/mocks/fines_mac_account_comments_and_notes_AY_mandatory_completed_mock.ts
  cypress/component/manualAccountCreation/FinesMacAccountCommentsAndNotes/mocks/fines_mac_account_comments_and_notes_AY_mandatory_missing_mock.ts
  cypress/component/manualAccountCreation/FinesMacAccountCommentsAndNotes/mocks/fines_mac_account_comments_and_notes_COMP_mandatory_completed_mock.ts
  cypress/component/manualAccountCreation/FinesMacAccountCommentsAndNotes/mocks/fines_mac_account_comments_and_notes_COMP_mandatory_missing_mock.ts
  cypress/component/manualAccountCreation/FinesMacAccountCommentsAndNotes/mocks/fines_mac_account_comments_and_notes_PG_mandatory_completed_mock.ts
  cypress/component/manualAccountCreation/FinesMacAccountCommentsAndNotes/mocks/fines_mac_account_comments_and_notes_PG_mandatory_missing_mock.ts
  cypress/component/manualAccountCreation/FinesMacAccountDetails/mocks/fines_mac_ayg_check_account_mock.ts
  cypress/component/manualAccountCreation/FinesMacAccountDetails/mocks/fines_mac_aypg_check_account_mock.ts
  cypress/component/manualAccountCreation/FinesMacAccountDetails/mocks/fines_mac_check_account_mock.ts
  cypress/component/manualAccountCreation/FinesMacAccountDetails/mocks/fines_mac_comp_check_account_mock.ts
  cypress/component/manualAccountCreation/FinesMacCompanyDetails/mocks/fines-mac-company-details-mock.ts
  cypress/component/manualAccountCreation/FinesMacCourtDetails/mocks/fines-mac-court-details-mock.ts
  cypress/component/manualAccountCreation/FinesMacCreateAccount/mocks/fines_mac_create_account_mock.ts
  cypress/component/manualAccountCreation/FinesMacEmployerDetails/mocks/fines-employer-details-mock.ts
  cypress/component/manualAccountCreation/FinesMacOffenceDetails/MinorCreditor/mocks/minor_creditor_fines_service_mock.ts
  cypress/component/manualAccountCreation/FinesMacOffenceDetails/MinorCreditorInformation/mocks/minor_creditor_information_mocks.ts
  cypress/component/manualAccountCreation/FinesMacOffenceDetails/ReviewSummary/mocks/review_summary_offence_mock.ts
  cypress/component/manualAccountCreation/FinesMacPaymentTerms/mocks/fines-payment-terms-mock.ts
  cypress/component/manualAccountCreation/FinesMacReviewAccount/mocks/fines_mac_review_account_mocks.ts
  cypress/e2e/functional/opal/fineAccountEnquiry/searchAndMatches/searchAndMatches.feature
  cypress/e2e/functional/opal/manualAccountCreation/checkAndValidate/checkAndValidateAccessibility.feature
  cypress/support/step_definitions/searchAndMatches/searchAndMatches.ts
  src/app/flows/fines/fines-sa/fines-sa-search/fines-sa-search-account/fines-sa-search-account-form/fines-sa-search-account-form-companies/constants/fines-sa-search-account-form-companies-controls.constant.ts
  src/app/flows/fines/fines-sa/fines-sa-search/fines-sa-search-account/fines-sa-search-account-form/fines-sa-search-account-form-companies/constants/fines-sa-search-account-form-companies-field-errors.constant.ts
  src/app/flows/fines/fines-sa/fines-sa-search/fines-sa-search-account/fines-sa-search-account-form/fines-sa-search-account-form-companies/constants/fines-sa-search-account-form-companies-state.constant.ts
  src/app/flows/fines/fines-sa/fines-sa-search/fines-sa-search-account/fines-sa-search-account-form/fines-sa-search-account-form-companies/constants/fines-sa-search-account-form-company-state.constant.ts
  src/app/flows/fines/fines-sa/fines-sa-search/fines-sa-search-account/fines-sa-search-account-form/fines-sa-search-account-form-companies/fines-sa-search-account-form-companies.component.html
  src/app/flows/fines/fines-sa/fines-sa-search/fines-sa-search-account/fines-sa-search-account-form/fines-sa-search-account-form-companies/fines-sa-search-account-form-companies.component.spec.ts
  src/app/flows/fines/fines-sa/fines-sa-search/fines-sa-search-account/fines-sa-search-account-form/fines-sa-search-account-form-companies/fines-sa-search-account-form-companies.component.ts
  src/app/flows/fines/fines-sa/fines-sa-search/fines-sa-search-account/fines-sa-search-account-form/fines-sa-search-account-form-companies/interfaces/fines-sa-search-account-form-companies-field-errors.interface.ts
  src/app/flows/fines/fines-sa/fines-sa-search/fines-sa-search-account/fines-sa-search-account-form/fines-sa-search-account-form-companies/interfaces/fines-sa-search-account-form-companies-state.interface.ts
  src/app/flows/fines/fines-sa/fines-sa-search/fines-sa-search-account/fines-sa-search-account-form/fines-sa-search-account-form-companies/interfaces/fines-sa-search-account-form-company-state.interface.ts
  src/app/flows/fines/fines-sa/fines-sa-search/fines-sa-search-account/fines-sa-search-account-form/fines-sa-search-account-form-individuals/fines-sa-search-account-form-individuals.component.spec.ts
  src/app/flows/fines/fines-sa/fines-sa-search/fines-sa-search-account/fines-sa-search-account-form/fines-sa-search-account-form-individuals/fines-sa-search-account-form-individuals.component.ts
  src/app/flows/fines/fines-sa/fines-sa-search/fines-sa-search-account/fines-sa-search-account-form/fines-sa-search-account-form.component.html
  src/app/flows/fines/fines-sa/fines-sa-search/fines-sa-search-account/fines-sa-search-account-form/fines-sa-search-account-form.component.scss
  src/app/flows/fines/fines-sa/fines-sa-search/fines-sa-search-account/fines-sa-search-account-form/fines-sa-search-account-form.component.spec.ts
  src/app/flows/fines/fines-sa/fines-sa-search/fines-sa-search-account/fines-sa-search-account-form/fines-sa-search-account-form.component.ts
  src/app/flows/fines/fines-sa/fines-sa-search/fines-sa-search-account/interfaces/fines-sa-search-account-state.interface.ts
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-1573

#1583 PO-1929
  cypress/fixtures/draftAccounts/adultOrYouthOnlyPayload.json
  cypress/fixtures/draftAccounts/approvedAccountPayload.json
  cypress/fixtures/draftAccounts/approvedCompanyPayload.json
  cypress/fixtures/draftAccounts/approvedParentOrGuardianPayload.json
  cypress/fixtures/draftAccounts/companyPayload.json
  cypress/fixtures/draftAccounts/parentOrGuardianPayload.json
  cypress/support/step_definitions/apiSteps/draftAccounts/addDraftAccount.ts
  src/app/flows/fines/fines-mac/services/fines-mac-payload/fines-mac-payload.service.spec.ts
  src/app/flows/fines/fines-mac/services/fines-mac-payload/fines-mac-payload.service.ts
  src/app/flows/fines/fines-mac/services/fines-mac-payload/mocks/fines-mac-payload-add-account.mock.ts
  src/app/flows/fines/fines-mac/services/fines-mac-payload/utils/fines-mac-payload-build-account/fines-mac-payload-build-account-offences.utils.spec.ts
  src/app/flows/fines/fines-mac/services/fines-mac-payload/utils/fines-mac-payload-build-account/fines-mac-payload-build-account-offences.utils.ts
  src/app/flows/fines/fines-mac/services/fines-mac-payload/utils/fines-mac-payload-map-account/fines-mac-payload-map-account-offences.utils.spec.ts
  src/app/flows/fines/fines-mac/services/fines-mac-payload/utils/mocks/fines-mac-payload-account-offences-with-major-creditor.mock.ts
  src/app/flows/fines/fines-mac/services/fines-mac-payload/utils/mocks/fines-mac-payload-account-offences-with-minor-creditor.mock.ts
  yarn-audit-known-issues
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-1583

#1591 PO-1906 - Adding Lint rule for ordering of members.
  .eslintrc.json
  README.md
  src/app/app.component.ts
  src/app/flows/fines/fines-draft/fines-draft-check-and-validate/fines-draft-check-and-validate-tabs/fines-draft-check-and-validate-tabs.component.ts
  src/app/flows/fines/fines-draft/fines-draft-create-and-manage/fines-draft-create-and-manage-tabs/fines-draft-create-and-manage-tabs.component.ts
  src/app/flows/fines/fines-draft/fines-draft-table-wrapper/fines-draft-table-wrapper.component.ts
  src/app/flows/fines/fines-mac/components/fines-mac-default-days/fines-mac-default-days.component.ts
  src/app/flows/fines/fines-mac/fines-mac-account-comments-notes/fines-mac-account-comments-notes-form/fines-mac-account-comments-notes-form.component.html
  src/app/flows/fines/fines-mac/fines-mac-account-comments-notes/fines-mac-account-comments-notes-form/fines-mac-account-comments-notes-form.component.ts
  src/app/flows/fines/fines-mac/fines-mac-account-details/fines-mac-account-details.component.spec.ts
  src/app/flows/fines/fines-mac/fines-mac-account-details/fines-mac-account-details.component.ts
  src/app/flows/fines/fines-mac/fines-mac-company-details/fines-mac-company-details-form/fines-mac-company-details-form.component.ts
  src/app/flows/fines/fines-mac/fines-mac-contact-details/fines-mac-contact-details-form/fines-mac-contact-details-form.component.ts
  src/app/flows/fines/fines-mac/fines-mac-court-details/fines-mac-court-details-form/fines-mac-court-details-form.component.ts
  src/app/flows/fines/fines-mac/fines-mac-court-details/fines-mac-court-details.component.ts
  src/app/flows/fines/fines-mac/fines-mac-create-account/fines-mac-create-account-form/fines-mac-create-account-form.component.ts
  src/app/flows/fines/fines-mac/fines-mac-delete-account-confirmation/fines-mac-delete-account-confirmation-form/fines-mac-delete-account-confirmation-form.component.ts
  src/app/flows/fines/fines-mac/fines-mac-delete-account-confirmation/fines-mac-delete-account-confirmation.component.ts
  src/app/flows/fines/fines-mac/fines-mac-employer-details/fines-mac-employer-details-form/fines-mac-employer-details-form.component.ts
  src/app/flows/fines/fines-mac/fines-mac-language-preferences/fines-mac-language-preferences-form/fines-mac-language-preferences-form.component.ts
  src/app/flows/fines/fines-mac/fines-mac-offence-details/fines-mac-offence-details-add-an-offence/fines-mac-offence-details-add-an-offence-form/fines-mac-offence-details-add-an-offence-form.component.ts
  src/app/flows/fines/fines-mac/fines-mac-offence-details/fines-mac-offence-details-minor-creditor-information/fines-mac-offence-details-minor-creditor-information.component.ts
  src/app/flows/fines/fines-mac/fines-mac-offence-details/fines-mac-offence-details-minor-creditor/fines-mac-offence-details-minor-creditor-form/fines-mac-offence-details-minor-creditor-form.component.ts
  src/app/flows/fines/fines-mac/fines-mac-offence-details/fines-mac-offence-details-review-offence/fines-mac-offence-details-review-offence-heading/fines-mac-offence-details-review-offence-heading.component.ts
  src/app/flows/fines/fines-mac/fines-mac-offence-details/fines-mac-offence-details-review-offence/fines-mac-offence-details-review-offence-imposition/fines-mac-offence-details-review-offence-imposition.component.ts
  src/app/flows/fines/fines-mac/fines-mac-offence-details/fines-mac-offence-details-review-offence/fines-mac-offence-details-review-offence.component.ts
  src/app/flows/fines/fines-mac/fines-mac-offence-details/fines-mac-offence-details-review/fines-mac-offence-details-review-summary/fines-mac-offence-details-review-summary-offences-total/fines-mac-offence-details-review-summary-offences-total.component.ts
  src/app/flows/fines/fines-mac/fines-mac-offence-details/fines-mac-offence-details-review/fines-mac-offence-details-review-summary/fines-mac-offence-details-review-summary.component.ts
  src/app/flows/fines/fines-mac/fines-mac-offence-details/fines-mac-offence-details-review/fines-mac-offence-details-review.component.ts
  src/app/flows/fines/fines-mac/fines-mac-offence-details/fines-mac-offence-details-search-offences/fines-mac-offence-details-search-offences-results/fines-mac-offence-details-search-offences-results-table-wrapper/fines-mac-offence-details-search-offences-results-table-wrapper.component.ts
  src/app/flows/fines/fines-mac/fines-mac-offence-details/fines-mac-offence-details-search-offences/fines-mac-offence-details-search-offences-results/fines-mac-offence-details-search-offences-results.component.ts
  src/app/flows/fines/fines-mac/fines-mac-offence-details/fines-mac-offence-details-search-offences/fines-mac-offence-details-search-offences-search/fines-mac-offence-details-search-offences-search-form/fines-mac-offence-details-search-offences-search-form.component.ts
  src/app/flows/fines/fines-mac/fines-mac-parent-guardian-details/fines-mac-parent-guardian-details-form/fines-mac-parent-guardian-details-form.component.ts
  src/app/flows/fines/fines-mac/fines-mac-payment-terms/fines-mac-payment-terms-form/fines-mac-payment-terms-form.component.ts
  src/app/flows/fines/fines-mac/fines-mac-personal-details/fines-mac-personal-details-form/fines-mac-personal-details-form.component.ts
  src/app/flows/fines/fines-mac/fines-mac-review-account/fines-mac-review-account-company-details/fines-mac-review-account-company-details.component.ts
  src/app/flows/fines/fines-mac/fines-mac-review-account/fines-mac-review-account-court-details/fines-mac-review-account-court-details.component.ts
  src/app/flows/fines/fines-mac/fines-mac-review-account/fines-mac-review-account-decision/fines-mac-review-account-decision-form/fines-mac-review-account-decision-form.component.ts
  src/app/flows/fines/fines-mac/fines-mac-review-account/fines-mac-review-account-decision/fines-mac-review-account-decision.component.ts
  src/app/flows/fines/fines-mac/fines-mac-review-account/fines-mac-review-account-employer-details/fines-mac-review-account-employer-details.component.ts
  src/app/flows/fines/fines-mac/fines-mac-review-account/fines-mac-review-account-history/fines-mac-review-account-history.component.ts
  src/app/flows/fines/fines-mac/fines-mac-review-account/fines-mac-review-account-parent-guardian-details/fines-mac-review-account-parent-guardian-details.component.ts
  src/app/flows/fines/fines-mac/fines-mac-review-account/fines-mac-review-account-payment-terms/fines-mac-review-account-payment-terms.component.ts
  src/app/flows/fines/fines-mac/fines-mac-review-account/fines-mac-review-account-personal-details/fines-mac-review-account-personal-details.component.ts
  src/app/flows/fines/fines-mac/services/fines-mac-payload/fines-mac-payload.service.ts
  src/app/flows/fines/fines-sa/fines-sa-search/fines-sa-search-account/fines-sa-search-account-form/fines-sa-search-account-form-individuals/fines-sa-search-account-form-individuals.component.ts
  src/app/flows/fines/fines-sa/fines-sa-search/fines-sa-search-account/fines-sa-search-account-form/fines-sa-search-account-form.component.ts
  src/app/pages/dashboard/dashboard.component.ts
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-1591

#1601 Enhance jenkins configuration
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  cypress.config.ts
  package.json
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-1601

#1602 further jenkins changes
  Jenkinsfile_nightly
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-1602

#1597 Update the permission service usage
  package.json
  src/app/flows/fines/fines-mac/fines-mac-payment-terms/fines-mac-payment-terms-form/fines-mac-payment-terms-form.component.spec.ts
  src/app/flows/fines/fines-mac/fines-mac-payment-terms/fines-mac-payment-terms-form/fines-mac-payment-terms-form.component.ts
  src/app/flows/fines/fines-mac/fines-mac-review-account/fines-mac-review-account-payment-terms/fines-mac-review-account-payment-terms.component.spec.ts
  src/app/flows/fines/fines-mac/fines-mac-review-account/fines-mac-review-account-payment-terms/fines-mac-review-account-payment-terms.component.ts
  yarn.lock
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-1597

#1584 PO-860
  src/app/flows/fines/fines-mac/fines-mac-company-details/constants/fines-mac-company-details-field-errors.ts
  src/app/flows/fines/fines-mac/fines-mac-fixed-penalty-details/constants/fines-mac-fixed-penalty-details-field-errors.ts
  src/app/flows/fines/fines-mac/fines-mac-fixed-penalty-details/constants/fines-mac-fixed-penalty-details-form-validators.ts
  src/app/flows/fines/fines-mac/fines-mac-fixed-penalty-details/constants/fines-mac-fixed-penalty-details-state.ts
  src/app/flows/fines/fines-mac/fines-mac-fixed-penalty-details/fines-mac-fixed-penalty-details-form/fines-mac-fixed-penalty-details-form.component.html
  src/app/flows/fines/fines-mac/fines-mac-fixed-penalty-details/fines-mac-fixed-penalty-details-form/fines-mac-fixed-penalty-details-form.component.spec.ts
  src/app/flows/fines/fines-mac/fines-mac-fixed-penalty-details/fines-mac-fixed-penalty-details-form/fines-mac-fixed-penalty-details-form.component.ts
  src/app/flows/fines/fines-mac/fines-mac-fixed-penalty-details/fines-mac-fixed-penalty-details.component.ts
  src/app/flows/fines/fines-mac/fines-mac-fixed-penalty-details/interfaces/fines-mac-fixed-penalty-details-field-errors.interface.ts
  src/app/flows/fines/fines-mac/fines-mac-fixed-penalty-details/interfaces/fines-mac-fixed-penalty-details-form-validators.interface.ts
  src/app/flows/fines/fines-mac/fines-mac-fixed-penalty-details/interfaces/fines-mac-fixed-penalty-details-state.interface.ts
  src/app/flows/fines/fines-mac/fines-mac-fixed-penalty-details/interfaces/fines-mac-fixed-penalty-details-store-state.interface.ts
  src/app/flows/fines/fines-mac/fines-mac-fixed-penalty-details/mocks/fines-mac-fixed-penalty-details-state.mock.ts
  src/app/flows/fines/fines-mac/services/fines-mac-payload/utils/interfaces/fines-mac-payload-fixed-penalty-details-state.interface.ts
  src/app/flows/fines/fines-mac/services/fines-mac-payload/utils/mocks/state/fines-mac-payload-fixed-penalty-details-state.mock.ts
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-1584

#1645 PO-1796: Align payload transformation object structure to ui lib
  package.json
  src/app/flows/fines/fines-mac/services/fines-mac-payload/constants/fines-mac-transform-items-config.constant.ts
  yarn.lock
Labels: ns:opal, prd:opal, skip_opal_component, rel:opal-frontend-pr-1645

#1644 Component test coverage for PO-860
  cypress/component/manualAccountCreation/FinesFixedPenalty/FinesMacManualFixedPenalty/FinesMacManualFixedPenalty.cy.ts
  cypress/component/manualAccountCreation/FinesFixedPenalty/FinesMacManualFixedPenalty/constants/fines_mac_manual_fixed_penalty_elements.ts
  cypress/e2e/functional/opal/manualAccountCreation/fixedPenalty/fixedPenalty.feature
Labels: ns:opal, prd:opal, rel:opal-frontend-pr-1644
